/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/characters/': RouteRecordInfo<
      '/characters/',
      '/characters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/characters/[character_id]': RouteRecordInfo<
      '/characters/[character_id]',
      '/characters/:character_id',
      { character_id: ParamValue<true> },
      { character_id: ParamValue<false> },
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/graph-example': RouteRecordInfo<
      '/graph-example',
      '/graph-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rooms/': RouteRecordInfo<
      '/rooms/',
      '/rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rooms/[room_id]': RouteRecordInfo<
      '/rooms/[room_id]',
      '/rooms/:room_id',
      { room_id: ParamValue<true> },
      { room_id: ParamValue<false> },
      | never
    >,
    '/scenarios/': RouteRecordInfo<
      '/scenarios/',
      '/scenarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scenarios/[scenario_id]': RouteRecordInfo<
      '/scenarios/[scenario_id]',
      '/scenarios/:scenario_id',
      { scenario_id: ParamValue<true> },
      { scenario_id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/characters/index.vue': {
      routes:
        | '/characters/'
      views:
        | never
    }
    'src/pages/characters/[character_id].vue': {
      routes:
        | '/characters/[character_id]'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/graph-example.vue': {
      routes:
        | '/graph-example'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/rooms/index.vue': {
      routes:
        | '/rooms/'
      views:
        | never
    }
    'src/pages/rooms/[room_id].vue': {
      routes:
        | '/rooms/[room_id]'
      views:
        | never
    }
    'src/pages/scenarios/index.vue': {
      routes:
        | '/scenarios/'
      views:
        | never
    }
    'src/pages/scenarios/[scenario_id].vue': {
      routes:
        | '/scenarios/[scenario_id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
