// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutResponses, AuthMeData, AuthMeResponses, AuthRegisterData, AuthRegisterErrors, AuthRegisterResponses, DocumentsDownloadOriginalDocumentData, DocumentsDownloadOriginalDocumentErrors, DocumentsDownloadOriginalDocumentResponses, DocumentsGetDocumentMarkdownData, DocumentsGetDocumentMarkdownErrors, DocumentsGetDocumentMarkdownResponses, DocumentsProcessDocumentData, DocumentsProcessDocumentErrors, DocumentsProcessDocumentResponses, RerankerRerankEndpointData, RerankerRerankEndpointErrors, RerankerRerankEndpointResponses, RoomsSendRoomMessageData, RoomsSendRoomMessageErrors, RoomsSendRoomMessageResponses, ScenariosCreateRoomData, ScenariosCreateRoomErrors, ScenariosCreateRoomResponses, ScenariosCreateScenarioData, ScenariosCreateScenarioErrors, ScenariosCreateScenarioResponses, ScenariosGetScenarioGraphData, ScenariosGetScenarioGraphErrors, ScenariosGetScenarioGraphResponses, ScenariosListScenarioDocumentsData, ScenariosListScenarioDocumentsErrors, ScenariosListScenarioDocumentsResponses, ScenariosListScenariosData, ScenariosListScenariosResponses, ScenariosUploadScenarioDocumentData, ScenariosUploadScenarioDocumentErrors, ScenariosUploadScenarioDocumentResponses, ToolsChunkPlainTextData, ToolsChunkPlainTextErrors, ToolsChunkPlainTextResponses, ToolsEntityExtractToolData, ToolsEntityExtractToolErrors, ToolsEntityExtractToolResponses, UsersGetAllData, UsersGetAllResponses, UsersGetMeData, UsersGetMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AuthService {
    /**
     * current user
     */
    public static me<ThrowOnError extends boolean = true>(options?: Options<AuthMeData, ThrowOnError>) {
        return (options?.client ?? client).get<AuthMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/me',
            ...options
        });
    }
    
    /**
     * login
     */
    public static login<ThrowOnError extends boolean = true>(options: Options<AuthLoginData, ThrowOnError>) {
        return (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
            responseType: 'json',
            url: '/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * logout
     */
    public static logout<ThrowOnError extends boolean = true>(options?: Options<AuthLogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/auth/logout',
            ...options
        });
    }
    
    /**
     * register
     */
    public static register<ThrowOnError extends boolean = true>(options: Options<AuthRegisterData, ThrowOnError>) {
        return (options.client ?? client).post<AuthRegisterResponses, AuthRegisterErrors, ThrowOnError>({
            responseType: 'json',
            url: '/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UsersService {
    /**
     * ...
     */
    public static getAll<ThrowOnError extends boolean = true>(options?: Options<UsersGetAllData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersGetAllResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/users',
            ...options
        });
    }
    
    /**
     * ...
     */
    public static getMe<ThrowOnError extends boolean = true>(options?: Options<UsersGetMeData, ThrowOnError>) {
        return (options?.client ?? client).get<UsersGetMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/users/me',
            ...options
        });
    }
}

export class RerankerService {
    /**
     * Cross-Encoder 重新排序
     */
    public static rerankEndpoint<ThrowOnError extends boolean = true>(options: Options<RerankerRerankEndpointData, ThrowOnError>) {
        return (options.client ?? client).post<RerankerRerankEndpointResponses, RerankerRerankEndpointErrors, ThrowOnError>({
            responseType: 'json',
            url: '/reranker/rerank',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ScenariosService {
    /**
     * 列出所有劇本
     */
    public static listScenarios<ThrowOnError extends boolean = true>(options?: Options<ScenariosListScenariosData, ThrowOnError>) {
        return (options?.client ?? client).get<ScenariosListScenariosResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/scenarios',
            ...options
        });
    }
    
    /**
     * 創建劇本
     */
    public static createScenario<ThrowOnError extends boolean = true>(options: Options<ScenariosCreateScenarioData, ThrowOnError>) {
        return (options.client ?? client).post<ScenariosCreateScenarioResponses, ScenariosCreateScenarioErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/scenarios',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 查看劇本中的文件
     */
    public static listScenarioDocuments<ThrowOnError extends boolean = true>(options: Options<ScenariosListScenarioDocumentsData, ThrowOnError>) {
        return (options.client ?? client).get<ScenariosListScenarioDocumentsResponses, ScenariosListScenarioDocumentsErrors, ThrowOnError>({
            responseType: 'json',
            url: '/scenarios/{scenario_id}/documents',
            ...options
        });
    }
    
    /**
     * 在劇本中上傳文件
     */
    public static uploadScenarioDocument<ThrowOnError extends boolean = true>(options: Options<ScenariosUploadScenarioDocumentData, ThrowOnError>) {
        return (options.client ?? client).post<ScenariosUploadScenarioDocumentResponses, ScenariosUploadScenarioDocumentErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            url: '/scenarios/{scenario_id}/documents',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * 在指定劇本建立跑團房間
     */
    public static createRoom<ThrowOnError extends boolean = true>(options: Options<ScenariosCreateRoomData, ThrowOnError>) {
        return (options.client ?? client).post<ScenariosCreateRoomResponses, ScenariosCreateRoomErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/scenarios/{scenario_id}/rooms',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 查看劇本的知識圖譜
     */
    public static getScenarioGraph<ThrowOnError extends boolean = true>(options: Options<ScenariosGetScenarioGraphData, ThrowOnError>) {
        return (options.client ?? client).get<ScenariosGetScenarioGraphResponses, ScenariosGetScenarioGraphErrors, ThrowOnError>({
            responseType: 'json',
            url: '/scenarios/{scenario_id}/graph',
            ...options
        });
    }
}

export class DocumentsService {
    /**
     * 查看指定文件的 Markdown 內容
     */
    public static getDocumentMarkdown<ThrowOnError extends boolean = true>(options: Options<DocumentsGetDocumentMarkdownData, ThrowOnError>) {
        return (options.client ?? client).get<DocumentsGetDocumentMarkdownResponses, DocumentsGetDocumentMarkdownErrors, ThrowOnError>({
            responseType: 'json',
            url: '/documents/{document_id}/md',
            ...options
        });
    }
    
    /**
     * 下載原始文件檔案
     */
    public static downloadOriginalDocument<ThrowOnError extends boolean = true>(options: Options<DocumentsDownloadOriginalDocumentData, ThrowOnError>) {
        return (options.client ?? client).get<DocumentsDownloadOriginalDocumentResponses, DocumentsDownloadOriginalDocumentErrors, ThrowOnError>({ url: '/documents/{document_id}/download', ...options });
    }
    
    /**
     * 處理文件（解析／索引等後續流程）
     */
    public static processDocument<ThrowOnError extends boolean = true>(options: Options<DocumentsProcessDocumentData, ThrowOnError>) {
        return (options.client ?? client).post<DocumentsProcessDocumentResponses, DocumentsProcessDocumentErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/documents/{document_id}/process',
            ...options
        });
    }
}

export class ToolsService {
    /**
     * 將純文字分塊（token-based）
     */
    public static chunkPlainText<ThrowOnError extends boolean = true>(options: Options<ToolsChunkPlainTextData, ThrowOnError>) {
        return (options.client ?? client).post<ToolsChunkPlainTextResponses, ToolsChunkPlainTextErrors, ThrowOnError>({
            responseType: 'json',
            url: '/tools/chunk-text',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * 提取實體
     */
    public static entityExtractTool<ThrowOnError extends boolean = true>(options: Options<ToolsEntityExtractToolData, ThrowOnError>) {
        return (options.client ?? client).post<ToolsEntityExtractToolResponses, ToolsEntityExtractToolErrors, ThrowOnError>({
            responseType: 'json',
            url: '/tools/entity-extract',
            ...options
        });
    }
}

export class RoomsService {
    /**
     * 在房間內傳送訊息
     */
    public static sendRoomMessage<ThrowOnError extends boolean = true>(options: Options<RoomsSendRoomMessageData, ThrowOnError>) {
        return (options.client ?? client).post<RoomsSendRoomMessageResponses, RoomsSendRoomMessageErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/rooms/{room_id}/messages',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
