// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://10.144.1.101:8000' | (string & {});
};

/**
 * Body_scenarios-upload_scenario_document
 */
export type BodyScenariosUploadScenarioDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CharacterDetailResponse
 */
export type CharacterDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Name
     */
    name: string;
    game_system: GameSystem;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Data
     */
    data?: CoCCharacterDataOutput | {
        [key: string]: unknown;
    } | null;
};

/**
 * CharacterResponse
 */
export type CharacterResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Name
     */
    name: string;
    game_system: GameSystem;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CharacterSkill
 */
export type CharacterSkillInput = {
    type: CoCSkillType;
    category: CoCSkillCategory;
    /**
     * Name
     */
    name: string;
    /**
     * Base Value
     */
    base_value?: number;
    /**
     * Occupation Value
     */
    occupation_value?: number;
    /**
     * Interest Value
     */
    interest_value?: number;
    /**
     * Adjustments
     */
    adjustments?: Array<SkillAdjustment>;
};

/**
 * CharacterSkill
 */
export type CharacterSkillOutput = {
    type: CoCSkillType;
    category: CoCSkillCategory;
    /**
     * Name
     */
    name: string;
    /**
     * Base Value
     */
    base_value?: number;
    /**
     * Occupation Value
     */
    occupation_value?: number;
    /**
     * Interest Value
     */
    interest_value?: number;
    /**
     * Adjustments
     */
    adjustments?: Array<SkillAdjustment>;
    /**
     * Total Value
     */
    readonly total_value: number;
};

/**
 * ChunkResponse
 */
export type ChunkResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Start Token
     */
    start_token: number;
    /**
     * End Token
     */
    end_token: number;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Index
     */
    index: number;
};

/**
 * ChunkTextRequest
 */
export type ChunkTextRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Chunk Size
     */
    chunk_size?: number;
    /**
     * Overlap
     */
    overlap?: number;
};

/**
 * ChunkTextResponse
 */
export type ChunkTextResponse = {
    /**
     * Chunks
     */
    chunks: Array<ChunkResponse>;
};

/**
 * CoCCharacterData
 *
 * COC 7th Edition 角色資料（存入 JSONB）
 */
export type CoCCharacterDataInput = {
    /**
     * Occupation
     */
    occupation?: string;
    occupational_features?: OccupationFeatureType;
    /**
     * Age
     */
    age?: number;
    /**
     * Gender
     */
    gender?: string;
    /**
     * Residence
     */
    residence?: string;
    /**
     * Birthplace
     */
    birthplace?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Hp
     */
    hp?: number;
    /**
     * Mp
     */
    mp?: number;
    /**
     * San
     */
    san?: number;
    /**
     * Luck
     */
    luck?: number;
    /**
     * Strength
     */
    strength?: number;
    /**
     * Constitution
     */
    constitution?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Dexterity
     */
    dexterity?: number;
    /**
     * Appearance
     */
    appearance?: number;
    /**
     * Intelligence
     */
    intelligence?: number;
    /**
     * Power
     */
    power?: number;
    /**
     * Education
     */
    education?: number;
    /**
     * Believer
     */
    believer?: boolean;
    /**
     * Cthulhu Mythos
     */
    cthulhu_mythos?: number;
    /**
     * Ideology Beliefs
     */
    ideology_beliefs?: string;
    /**
     * Significant People
     */
    significant_people?: string;
    /**
     * Meaningful Locations
     */
    meaningful_locations?: string;
    /**
     * Treasured Possessions
     */
    treasured_possessions?: string;
    /**
     * Traits
     */
    traits?: string;
    /**
     * Bonds
     */
    bonds?: string;
    /**
     * Skills
     */
    skills?: Array<CharacterSkillInput>;
    /**
     * Skill Adjustments
     */
    skill_adjustments?: Array<SkillAdjustment>;
};

/**
 * CoCCharacterData
 *
 * COC 7th Edition 角色資料（存入 JSONB）
 */
export type CoCCharacterDataOutput = {
    /**
     * Occupation
     */
    occupation?: string;
    occupational_features?: OccupationFeatureType;
    /**
     * Age
     */
    age?: number;
    /**
     * Gender
     */
    gender?: string;
    /**
     * Residence
     */
    residence?: string;
    /**
     * Birthplace
     */
    birthplace?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Hp
     */
    hp?: number;
    /**
     * Mp
     */
    mp?: number;
    /**
     * San
     */
    san?: number;
    /**
     * Luck
     */
    luck?: number;
    /**
     * Strength
     */
    strength?: number;
    /**
     * Constitution
     */
    constitution?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Dexterity
     */
    dexterity?: number;
    /**
     * Appearance
     */
    appearance?: number;
    /**
     * Intelligence
     */
    intelligence?: number;
    /**
     * Power
     */
    power?: number;
    /**
     * Education
     */
    education?: number;
    /**
     * Believer
     */
    believer?: boolean;
    /**
     * Cthulhu Mythos
     */
    cthulhu_mythos?: number;
    /**
     * Ideology Beliefs
     */
    ideology_beliefs?: string;
    /**
     * Significant People
     */
    significant_people?: string;
    /**
     * Meaningful Locations
     */
    meaningful_locations?: string;
    /**
     * Treasured Possessions
     */
    treasured_possessions?: string;
    /**
     * Traits
     */
    traits?: string;
    /**
     * Bonds
     */
    bonds?: string;
    /**
     * Skills
     */
    skills?: Array<CharacterSkillOutput>;
    /**
     * Skill Adjustments
     */
    skill_adjustments?: Array<SkillAdjustment>;
};

/**
 * CoCSkillAdjustmentType
 *
 * COC 技能調整來源
 */
export type CoCSkillAdjustmentType = 'GROWTH' | 'CUSTOM';

/**
 * CoCSkillCategory
 *
 * COC 技能分類
 */
export type CoCSkillCategory = 'NEGOTIATION' | 'INVESTIGATION' | 'LANGUAGE' | 'MEDICAL' | 'PILOT' | 'SURVIVAL' | 'ART_AND_CRAFT' | 'SCIENCE' | 'CUSTOM';

/**
 * CoCSkillType
 *
 * COC 技能類型
 */
export type CoCSkillType = 'STANDARD' | 'DERIVED' | 'CUSTOM';

/**
 * CreateCharacterRequest
 */
export type CreateCharacterRequest = {
    /**
     * Name
     */
    name: string;
    game_system?: GameSystem;
    data?: CoCCharacterDataInput;
};

/**
 * CreateRoomRequest
 */
export type CreateRoomRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CreateScenarioRequest
 */
export type CreateScenarioRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System
     *
     * COC, DND, etc.
     */
    system: string;
    /**
     * Min Players
     */
    min_players?: number | null;
    /**
     * Max Players
     */
    max_players?: number | null;
    /**
     * Min Hours
     */
    min_hours?: number | null;
    /**
     * Max Hours
     */
    max_hours?: number | null;
};

/**
 * DocumentMarkdownResponse
 */
export type DocumentMarkdownResponse = {
    /**
     * Content
     */
    content: string;
};

/**
 * DocumentResponse
 */
export type DocumentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Md Path
     */
    md_path: string | null;
    status: DocumentStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DocumentStatus
 */
export type DocumentStatus = 'READY' | 'PROCESSING' | 'COMPLETED' | 'FAILED';

/**
 * GameSystem
 */
export type GameSystem = 'COC' | 'DND';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JoinRoomRequest
 */
export type JoinRoomRequest = {
    /**
     * Invite Code
     */
    invite_code: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MeResponse
 */
export type MeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
};

/**
 * OccupationFeatureType
 *
 * COC 職業技能點計算方式
 */
export type OccupationFeatureType = 'EDU' | 'EDU_STR' | 'EDU_DEX' | 'EDU_APP' | 'EDU_POW';

/**
 * ProcessDocumentResponse
 */
export type ProcessDocumentResponse = {
    /**
     * Document Id
     */
    document_id: string;
    status: DocumentStatus;
    /**
     * Message
     */
    message: string;
    /**
     * Entities
     */
    entities: Array<unknown>;
    /**
     * Relationships
     */
    relationships: Array<unknown>;
};

/**
 * RankedDocument
 */
export type RankedDocument = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Score
     */
    score: number;
    /**
     * Document
     */
    document: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RerankRequest
 */
export type RerankRequest = {
    /**
     * Query
     *
     * 查詢字串
     */
    query: string;
    /**
     * Documents
     *
     * 待排序的文件清單
     */
    documents: Array<string>;
};

/**
 * RerankResponse
 */
export type RerankResponse = {
    /**
     * Ranked Documents
     */
    ranked_documents: Array<RankedDocument>;
};

/**
 * RoomDetailResponse
 */
export type RoomDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Host Id
     */
    host_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    status: RoomStatus;
    /**
     * Invite Code
     */
    invite_code: string;
    /**
     * Participants
     */
    participants: Array<RoomParticipantResponse>;
};

/**
 * RoomMessageResponse
 */
export type RoomMessageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Room Id
     */
    room_id: string;
    /**
     * Sender Id
     */
    sender_id: string | null;
    role: RoomMessageRole;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RoomMessageRole
 */
export type RoomMessageRole = 'AGENT' | 'PLAYER' | 'SYSTEM';

/**
 * RoomParticipantResponse
 */
export type RoomParticipantResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Is Ready
     */
    is_ready: boolean;
    /**
     * Joined At
     */
    joined_at: string;
};

/**
 * RoomResponse
 */
export type RoomResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Host Id
     */
    host_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    status: RoomStatus;
    /**
     * Invite Code
     */
    invite_code: string;
};

/**
 * RoomStatus
 */
export type RoomStatus = 'PREPARING' | 'RUNNING' | 'COMPLETED';

/**
 * ScenarioGraphEdgeResponse
 */
export type ScenarioGraphEdgeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Source
     */
    source: string;
    /**
     * Target
     */
    target: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Directed
     */
    directed?: boolean;
};

/**
 * ScenarioGraphNodeResponse
 */
export type ScenarioGraphNodeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * ScenarioGraphResponse
 */
export type ScenarioGraphResponse = {
    /**
     * Nodes
     */
    nodes: Array<ScenarioGraphNodeResponse>;
    /**
     * Edges
     */
    edges: Array<ScenarioGraphEdgeResponse>;
};

/**
 * ScenarioResponse
 */
export type ScenarioResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System
     */
    system: string;
    /**
     * Min Players
     */
    min_players: number | null;
    /**
     * Max Players
     */
    max_players: number | null;
    /**
     * Min Hours
     */
    min_hours: number | null;
    /**
     * Max Hours
     */
    max_hours: number | null;
    /**
     * Creator Id
     */
    creator_id: string;
    status: ScenarioStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ScenarioStatus
 */
export type ScenarioStatus = 'DRAFT' | 'PUBLISHED';

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * SkillAdjustment
 */
export type SkillAdjustment = {
    type: CoCSkillAdjustmentType;
    /**
     * Value
     */
    value: number;
    /**
     * Note
     */
    note?: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdateCharacterRequest
 */
export type UpdateCharacterRequest = {
    /**
     * Name
     */
    name?: string | null;
    data?: CoCCharacterDataInput | null;
};

/**
 * UpdateScenarioRequest
 */
export type UpdateScenarioRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System
     */
    system?: string | null;
    /**
     * Min Players
     */
    min_players?: number | null;
    /**
     * Max Players
     */
    max_players?: number | null;
    /**
     * Min Hours
     */
    min_hours?: number | null;
    /**
     * Max Hours
     */
    max_hours?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WsTicketResponse
 */
export type WsTicketResponse = {
    /**
     * Ticket
     */
    ticket: string;
    /**
     * Expires In Seconds
     */
    expires_in_seconds: number;
};

/**
 * CharacterDetailResponse
 */
export type CharacterDetailResponseWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Name
     */
    name: string;
    game_system: GameSystem;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Data
     */
    data?: CoCCharacterDataOutputWritable | {
        [key: string]: unknown;
    } | null;
};

/**
 * CharacterSkill
 */
export type CharacterSkillOutputWritable = {
    type: CoCSkillType;
    category: CoCSkillCategory;
    /**
     * Name
     */
    name: string;
    /**
     * Base Value
     */
    base_value?: number;
    /**
     * Occupation Value
     */
    occupation_value?: number;
    /**
     * Interest Value
     */
    interest_value?: number;
    /**
     * Adjustments
     */
    adjustments?: Array<SkillAdjustment>;
};

/**
 * CoCCharacterData
 *
 * COC 7th Edition 角色資料（存入 JSONB）
 */
export type CoCCharacterDataOutputWritable = {
    /**
     * Occupation
     */
    occupation?: string;
    occupational_features?: OccupationFeatureType;
    /**
     * Age
     */
    age?: number;
    /**
     * Gender
     */
    gender?: string;
    /**
     * Residence
     */
    residence?: string;
    /**
     * Birthplace
     */
    birthplace?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Hp
     */
    hp?: number;
    /**
     * Mp
     */
    mp?: number;
    /**
     * San
     */
    san?: number;
    /**
     * Luck
     */
    luck?: number;
    /**
     * Strength
     */
    strength?: number;
    /**
     * Constitution
     */
    constitution?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Dexterity
     */
    dexterity?: number;
    /**
     * Appearance
     */
    appearance?: number;
    /**
     * Intelligence
     */
    intelligence?: number;
    /**
     * Power
     */
    power?: number;
    /**
     * Education
     */
    education?: number;
    /**
     * Believer
     */
    believer?: boolean;
    /**
     * Cthulhu Mythos
     */
    cthulhu_mythos?: number;
    /**
     * Ideology Beliefs
     */
    ideology_beliefs?: string;
    /**
     * Significant People
     */
    significant_people?: string;
    /**
     * Meaningful Locations
     */
    meaningful_locations?: string;
    /**
     * Treasured Possessions
     */
    treasured_possessions?: string;
    /**
     * Traits
     */
    traits?: string;
    /**
     * Bonds
     */
    bonds?: string;
    /**
     * Skills
     */
    skills?: Array<CharacterSkillOutputWritable>;
    /**
     * Skill Adjustments
     */
    skill_adjustments?: Array<SkillAdjustment>;
};

export type WebsocketIssueWsTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/websocket/ticket';
};

export type WebsocketIssueWsTicketResponses = {
    /**
     * Successful Response
     */
    200: WsTicketResponse;
};

export type WebsocketIssueWsTicketResponse = WebsocketIssueWsTicketResponses[keyof WebsocketIssueWsTicketResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Response Auth-Logout
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type MeListMyRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/rooms';
};

export type MeListMyRoomsResponses = {
    /**
     * Response Me-List My Rooms
     *
     * Successful Response
     */
    200: Array<RoomResponse>;
};

export type MeListMyRoomsResponse = MeListMyRoomsResponses[keyof MeListMyRoomsResponses];

export type UsersGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersGetAllResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersGetMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RerankerRerankEndpointData = {
    body: RerankRequest;
    path?: never;
    query?: never;
    url: '/reranker/rerank';
};

export type RerankerRerankEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RerankerRerankEndpointError = RerankerRerankEndpointErrors[keyof RerankerRerankEndpointErrors];

export type RerankerRerankEndpointResponses = {
    /**
     * Successful Response
     */
    200: RerankResponse;
};

export type RerankerRerankEndpointResponse = RerankerRerankEndpointResponses[keyof RerankerRerankEndpointResponses];

export type ScenariosListScenariosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scenarios';
};

export type ScenariosListScenariosResponses = {
    /**
     * Response Scenarios-List Scenarios
     *
     * Successful Response
     */
    200: Array<ScenarioResponse>;
};

export type ScenariosListScenariosResponse = ScenariosListScenariosResponses[keyof ScenariosListScenariosResponses];

export type ScenariosCreateScenarioData = {
    body: CreateScenarioRequest;
    path?: never;
    query?: never;
    url: '/scenarios';
};

export type ScenariosCreateScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosCreateScenarioError = ScenariosCreateScenarioErrors[keyof ScenariosCreateScenarioErrors];

export type ScenariosCreateScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosCreateScenarioResponse = ScenariosCreateScenarioResponses[keyof ScenariosCreateScenarioResponses];

export type ScenariosGetScenarioData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}';
};

export type ScenariosGetScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosGetScenarioError = ScenariosGetScenarioErrors[keyof ScenariosGetScenarioErrors];

export type ScenariosGetScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosGetScenarioResponse = ScenariosGetScenarioResponses[keyof ScenariosGetScenarioResponses];

export type ScenariosUpdateScenarioData = {
    body: UpdateScenarioRequest;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}';
};

export type ScenariosUpdateScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosUpdateScenarioError = ScenariosUpdateScenarioErrors[keyof ScenariosUpdateScenarioErrors];

export type ScenariosUpdateScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosUpdateScenarioResponse = ScenariosUpdateScenarioResponses[keyof ScenariosUpdateScenarioResponses];

export type ScenariosPublishScenarioData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/publish';
};

export type ScenariosPublishScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosPublishScenarioError = ScenariosPublishScenarioErrors[keyof ScenariosPublishScenarioErrors];

export type ScenariosPublishScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosPublishScenarioResponse = ScenariosPublishScenarioResponses[keyof ScenariosPublishScenarioResponses];

export type ScenariosListScenarioDocumentsData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/documents';
};

export type ScenariosListScenarioDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosListScenarioDocumentsError = ScenariosListScenarioDocumentsErrors[keyof ScenariosListScenarioDocumentsErrors];

export type ScenariosListScenarioDocumentsResponses = {
    /**
     * Response Scenarios-List Scenario Documents
     *
     * Successful Response
     */
    200: Array<DocumentResponse>;
};

export type ScenariosListScenarioDocumentsResponse = ScenariosListScenarioDocumentsResponses[keyof ScenariosListScenarioDocumentsResponses];

export type ScenariosUploadScenarioDocumentData = {
    body: BodyScenariosUploadScenarioDocument;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/documents';
};

export type ScenariosUploadScenarioDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosUploadScenarioDocumentError = ScenariosUploadScenarioDocumentErrors[keyof ScenariosUploadScenarioDocumentErrors];

export type ScenariosUploadScenarioDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponse;
};

export type ScenariosUploadScenarioDocumentResponse = ScenariosUploadScenarioDocumentResponses[keyof ScenariosUploadScenarioDocumentResponses];

export type ScenariosCreateRoomData = {
    body: CreateRoomRequest;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/rooms';
};

export type ScenariosCreateRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosCreateRoomError = ScenariosCreateRoomErrors[keyof ScenariosCreateRoomErrors];

export type ScenariosCreateRoomResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type ScenariosCreateRoomResponse = ScenariosCreateRoomResponses[keyof ScenariosCreateRoomResponses];

export type ScenariosGetScenarioGraphData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/graph';
};

export type ScenariosGetScenarioGraphErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosGetScenarioGraphError = ScenariosGetScenarioGraphErrors[keyof ScenariosGetScenarioGraphErrors];

export type ScenariosGetScenarioGraphResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGraphResponse;
};

export type ScenariosGetScenarioGraphResponse = ScenariosGetScenarioGraphResponses[keyof ScenariosGetScenarioGraphResponses];

export type DocumentsGetDocumentMarkdownData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/md';
};

export type DocumentsGetDocumentMarkdownErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentMarkdownError = DocumentsGetDocumentMarkdownErrors[keyof DocumentsGetDocumentMarkdownErrors];

export type DocumentsGetDocumentMarkdownResponses = {
    /**
     * Successful Response
     */
    200: DocumentMarkdownResponse;
};

export type DocumentsGetDocumentMarkdownResponse = DocumentsGetDocumentMarkdownResponses[keyof DocumentsGetDocumentMarkdownResponses];

export type DocumentsDownloadOriginalDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/download';
};

export type DocumentsDownloadOriginalDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDownloadOriginalDocumentError = DocumentsDownloadOriginalDocumentErrors[keyof DocumentsDownloadOriginalDocumentErrors];

export type DocumentsDownloadOriginalDocumentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsProcessDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/process';
};

export type DocumentsProcessDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsProcessDocumentError = DocumentsProcessDocumentErrors[keyof DocumentsProcessDocumentErrors];

export type DocumentsProcessDocumentResponses = {
    /**
     * Successful Response
     */
    200: ProcessDocumentResponse;
};

export type DocumentsProcessDocumentResponse = DocumentsProcessDocumentResponses[keyof DocumentsProcessDocumentResponses];

export type ToolsChunkPlainTextData = {
    body: ChunkTextRequest;
    path?: never;
    query?: never;
    url: '/tools/chunk-text';
};

export type ToolsChunkPlainTextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToolsChunkPlainTextError = ToolsChunkPlainTextErrors[keyof ToolsChunkPlainTextErrors];

export type ToolsChunkPlainTextResponses = {
    /**
     * Successful Response
     */
    200: ChunkTextResponse;
};

export type ToolsChunkPlainTextResponse = ToolsChunkPlainTextResponses[keyof ToolsChunkPlainTextResponses];

export type ToolsEntityExtractToolData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Text
         */
        text: string;
    };
    url: '/tools/entity-extract';
};

export type ToolsEntityExtractToolErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToolsEntityExtractToolError = ToolsEntityExtractToolErrors[keyof ToolsEntityExtractToolErrors];

export type ToolsEntityExtractToolResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RoomsGetRoomData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}';
};

export type RoomsGetRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsGetRoomError = RoomsGetRoomErrors[keyof RoomsGetRoomErrors];

export type RoomsGetRoomResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsGetRoomResponse = RoomsGetRoomResponses[keyof RoomsGetRoomResponses];

export type RoomsJoinRoomData = {
    body: JoinRoomRequest;
    path?: never;
    query?: never;
    url: '/rooms/join';
};

export type RoomsJoinRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsJoinRoomError = RoomsJoinRoomErrors[keyof RoomsJoinRoomErrors];

export type RoomsJoinRoomResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsJoinRoomResponse = RoomsJoinRoomResponses[keyof RoomsJoinRoomResponses];

export type RoomsRegenerateInviteCodeData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/invite-code/regenerate';
};

export type RoomsRegenerateInviteCodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsRegenerateInviteCodeError = RoomsRegenerateInviteCodeErrors[keyof RoomsRegenerateInviteCodeErrors];

export type RoomsRegenerateInviteCodeResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsRegenerateInviteCodeResponse = RoomsRegenerateInviteCodeResponses[keyof RoomsRegenerateInviteCodeResponses];

export type RoomsKickParticipantData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/participants/{user_id}';
};

export type RoomsKickParticipantErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsKickParticipantError = RoomsKickParticipantErrors[keyof RoomsKickParticipantErrors];

export type RoomsKickParticipantResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsKickParticipantResponse = RoomsKickParticipantResponses[keyof RoomsKickParticipantResponses];

export type RoomsSetReadyData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query: {
        /**
         * Is Ready
         */
        is_ready: boolean;
    };
    url: '/rooms/{room_id}/ready';
};

export type RoomsSetReadyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsSetReadyError = RoomsSetReadyErrors[keyof RoomsSetReadyErrors];

export type RoomsSetReadyResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsSetReadyResponse = RoomsSetReadyResponses[keyof RoomsSetReadyResponses];

export type RoomsStartSessionData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/start';
};

export type RoomsStartSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsStartSessionError = RoomsStartSessionErrors[keyof RoomsStartSessionErrors];

export type RoomsStartSessionResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsStartSessionResponse = RoomsStartSessionResponses[keyof RoomsStartSessionResponses];

export type RoomsListRoomMessagesData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/messages';
};

export type RoomsListRoomMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsListRoomMessagesError = RoomsListRoomMessagesErrors[keyof RoomsListRoomMessagesErrors];

export type RoomsListRoomMessagesResponses = {
    /**
     * Response Rooms-List Room Messages
     *
     * Successful Response
     */
    200: Array<RoomMessageResponse>;
};

export type RoomsListRoomMessagesResponse = RoomsListRoomMessagesResponses[keyof RoomsListRoomMessagesResponses];

export type RoomsSendRoomMessageData = {
    body: SendMessageRequest;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/messages';
};

export type RoomsSendRoomMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsSendRoomMessageError = RoomsSendRoomMessageErrors[keyof RoomsSendRoomMessageErrors];

export type RoomsSendRoomMessageResponses = {
    /**
     * Successful Response
     */
    200: RoomMessageResponse;
};

export type RoomsSendRoomMessageResponse = RoomsSendRoomMessageResponses[keyof RoomsSendRoomMessageResponses];

export type CharactersListCharactersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/characters';
};

export type CharactersListCharactersResponses = {
    /**
     * Response Characters-List Characters
     *
     * Successful Response
     */
    200: Array<CharacterResponse>;
};

export type CharactersListCharactersResponse = CharactersListCharactersResponses[keyof CharactersListCharactersResponses];

export type CharactersCreateCharacterData = {
    body: CreateCharacterRequest;
    path?: never;
    query?: never;
    url: '/characters';
};

export type CharactersCreateCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersCreateCharacterError = CharactersCreateCharacterErrors[keyof CharactersCreateCharacterErrors];

export type CharactersCreateCharacterResponses = {
    /**
     * Successful Response
     */
    201: CharacterDetailResponse;
};

export type CharactersCreateCharacterResponse = CharactersCreateCharacterResponses[keyof CharactersCreateCharacterResponses];

export type CharactersDeleteCharacterData = {
    body?: never;
    path: {
        /**
         * Character Id
         */
        character_id: string;
    };
    query?: never;
    url: '/characters/{character_id}';
};

export type CharactersDeleteCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersDeleteCharacterError = CharactersDeleteCharacterErrors[keyof CharactersDeleteCharacterErrors];

export type CharactersDeleteCharacterResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CharactersDeleteCharacterResponse = CharactersDeleteCharacterResponses[keyof CharactersDeleteCharacterResponses];

export type CharactersGetCharacterData = {
    body?: never;
    path: {
        /**
         * Character Id
         */
        character_id: string;
    };
    query?: never;
    url: '/characters/{character_id}';
};

export type CharactersGetCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersGetCharacterError = CharactersGetCharacterErrors[keyof CharactersGetCharacterErrors];

export type CharactersGetCharacterResponses = {
    /**
     * Successful Response
     */
    200: CharacterDetailResponse;
};

export type CharactersGetCharacterResponse = CharactersGetCharacterResponses[keyof CharactersGetCharacterResponses];

export type CharactersUpdateCharacterData = {
    body: UpdateCharacterRequest;
    path: {
        /**
         * Character Id
         */
        character_id: string;
    };
    query?: never;
    url: '/characters/{character_id}';
};

export type CharactersUpdateCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersUpdateCharacterError = CharactersUpdateCharacterErrors[keyof CharactersUpdateCharacterErrors];

export type CharactersUpdateCharacterResponses = {
    /**
     * Successful Response
     */
    200: CharacterDetailResponse;
};

export type CharactersUpdateCharacterResponse = CharactersUpdateCharacterResponses[keyof CharactersUpdateCharacterResponses];
