// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Body_scenarios-upload_scenario_document
 */
export type BodyScenariosUploadScenarioDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChunkResponse
 */
export type ChunkResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Start Token
     */
    start_token: number;
    /**
     * End Token
     */
    end_token: number;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Index
     */
    index: number;
};

/**
 * ChunkTextRequest
 */
export type ChunkTextRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Chunk Size
     */
    chunk_size?: number;
    /**
     * Overlap
     */
    overlap?: number;
};

/**
 * ChunkTextResponse
 */
export type ChunkTextResponse = {
    /**
     * Chunks
     */
    chunks: Array<ChunkResponse>;
};

/**
 * CreateRoomRequest
 */
export type CreateRoomRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CreateScenarioRequest
 */
export type CreateScenarioRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System
     *
     * COC, DND, etc.
     */
    system: string;
    /**
     * Min Players
     */
    min_players?: number | null;
    /**
     * Max Players
     */
    max_players?: number | null;
    /**
     * Min Hours
     */
    min_hours?: number | null;
    /**
     * Max Hours
     */
    max_hours?: number | null;
};

/**
 * DocumentMarkdownResponse
 */
export type DocumentMarkdownResponse = {
    /**
     * Content
     */
    content: string;
};

/**
 * DocumentResponse
 */
export type DocumentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Md Path
     */
    md_path: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ProcessDocumentResponse
 */
export type ProcessDocumentResponse = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * RankedDocument
 */
export type RankedDocument = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Score
     */
    score: number;
    /**
     * Document
     */
    document: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RerankRequest
 */
export type RerankRequest = {
    /**
     * Query
     *
     * 查詢字串
     */
    query: string;
    /**
     * Documents
     *
     * 待排序的文件清單
     */
    documents: Array<string>;
};

/**
 * RerankResponse
 */
export type RerankResponse = {
    /**
     * Ranked Documents
     */
    ranked_documents: Array<RankedDocument>;
};

/**
 * RoomMessageResponse
 */
export type RoomMessageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Room Id
     */
    room_id: string;
    /**
     * Sender Id
     */
    sender_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RoomResponse
 */
export type RoomResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Host Id
     */
    host_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * ScenarioResponse
 */
export type ScenarioResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System
     */
    system: string;
    /**
     * Min Players
     */
    min_players: number | null;
    /**
     * Max Players
     */
    max_players: number | null;
    /**
     * Min Hours
     */
    min_hours: number | null;
    /**
     * Max Hours
     */
    max_hours: number | null;
    /**
     * Creator Id
     */
    creator_id: string;
};

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Response Auth-Logout
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type UsersGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersGetAllResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersGetMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RerankerRerankEndpointData = {
    body: RerankRequest;
    path?: never;
    query?: never;
    url: '/reranker/rerank';
};

export type RerankerRerankEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RerankerRerankEndpointError = RerankerRerankEndpointErrors[keyof RerankerRerankEndpointErrors];

export type RerankerRerankEndpointResponses = {
    /**
     * Successful Response
     */
    200: RerankResponse;
};

export type RerankerRerankEndpointResponse = RerankerRerankEndpointResponses[keyof RerankerRerankEndpointResponses];

export type ScenariosListScenariosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scenarios';
};

export type ScenariosListScenariosResponses = {
    /**
     * Response Scenarios-List Scenarios
     *
     * Successful Response
     */
    200: Array<ScenarioResponse>;
};

export type ScenariosListScenariosResponse = ScenariosListScenariosResponses[keyof ScenariosListScenariosResponses];

export type ScenariosCreateScenarioData = {
    body: CreateScenarioRequest;
    path?: never;
    query?: never;
    url: '/scenarios';
};

export type ScenariosCreateScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosCreateScenarioError = ScenariosCreateScenarioErrors[keyof ScenariosCreateScenarioErrors];

export type ScenariosCreateScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosCreateScenarioResponse = ScenariosCreateScenarioResponses[keyof ScenariosCreateScenarioResponses];

export type ScenariosListScenarioDocumentsData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/documents';
};

export type ScenariosListScenarioDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosListScenarioDocumentsError = ScenariosListScenarioDocumentsErrors[keyof ScenariosListScenarioDocumentsErrors];

export type ScenariosListScenarioDocumentsResponses = {
    /**
     * Response Scenarios-List Scenario Documents
     *
     * Successful Response
     */
    200: Array<DocumentResponse>;
};

export type ScenariosListScenarioDocumentsResponse = ScenariosListScenarioDocumentsResponses[keyof ScenariosListScenarioDocumentsResponses];

export type ScenariosUploadScenarioDocumentData = {
    body: BodyScenariosUploadScenarioDocument;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/documents';
};

export type ScenariosUploadScenarioDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosUploadScenarioDocumentError = ScenariosUploadScenarioDocumentErrors[keyof ScenariosUploadScenarioDocumentErrors];

export type ScenariosUploadScenarioDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponse;
};

export type ScenariosUploadScenarioDocumentResponse = ScenariosUploadScenarioDocumentResponses[keyof ScenariosUploadScenarioDocumentResponses];

export type ScenariosCreateRoomData = {
    body: CreateRoomRequest;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/rooms';
};

export type ScenariosCreateRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosCreateRoomError = ScenariosCreateRoomErrors[keyof ScenariosCreateRoomErrors];

export type ScenariosCreateRoomResponses = {
    /**
     * Successful Response
     */
    200: RoomResponse;
};

export type ScenariosCreateRoomResponse = ScenariosCreateRoomResponses[keyof ScenariosCreateRoomResponses];

export type ScenariosGetScenarioGraphData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/graph';
};

export type ScenariosGetScenarioGraphErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosGetScenarioGraphError = ScenariosGetScenarioGraphErrors[keyof ScenariosGetScenarioGraphErrors];

export type ScenariosGetScenarioGraphResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsGetDocumentMarkdownData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/md';
};

export type DocumentsGetDocumentMarkdownErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentMarkdownError = DocumentsGetDocumentMarkdownErrors[keyof DocumentsGetDocumentMarkdownErrors];

export type DocumentsGetDocumentMarkdownResponses = {
    /**
     * Successful Response
     */
    200: DocumentMarkdownResponse;
};

export type DocumentsGetDocumentMarkdownResponse = DocumentsGetDocumentMarkdownResponses[keyof DocumentsGetDocumentMarkdownResponses];

export type DocumentsDownloadOriginalDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/download';
};

export type DocumentsDownloadOriginalDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDownloadOriginalDocumentError = DocumentsDownloadOriginalDocumentErrors[keyof DocumentsDownloadOriginalDocumentErrors];

export type DocumentsDownloadOriginalDocumentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsProcessDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/process';
};

export type DocumentsProcessDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsProcessDocumentError = DocumentsProcessDocumentErrors[keyof DocumentsProcessDocumentErrors];

export type DocumentsProcessDocumentResponses = {
    /**
     * Successful Response
     */
    200: ProcessDocumentResponse;
};

export type DocumentsProcessDocumentResponse = DocumentsProcessDocumentResponses[keyof DocumentsProcessDocumentResponses];

export type ToolsChunkPlainTextData = {
    body: ChunkTextRequest;
    path?: never;
    query?: never;
    url: '/tools/chunk-text';
};

export type ToolsChunkPlainTextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToolsChunkPlainTextError = ToolsChunkPlainTextErrors[keyof ToolsChunkPlainTextErrors];

export type ToolsChunkPlainTextResponses = {
    /**
     * Successful Response
     */
    200: ChunkTextResponse;
};

export type ToolsChunkPlainTextResponse = ToolsChunkPlainTextResponses[keyof ToolsChunkPlainTextResponses];

export type ToolsEntityExtractToolData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Text
         */
        text: string;
    };
    url: '/tools/entity-extract';
};

export type ToolsEntityExtractToolErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToolsEntityExtractToolError = ToolsEntityExtractToolErrors[keyof ToolsEntityExtractToolErrors];

export type ToolsEntityExtractToolResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RoomsSendRoomMessageData = {
    body: SendMessageRequest;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/messages';
};

export type RoomsSendRoomMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsSendRoomMessageError = RoomsSendRoomMessageErrors[keyof RoomsSendRoomMessageErrors];

export type RoomsSendRoomMessageResponses = {
    /**
     * Successful Response
     */
    200: RoomMessageResponse;
};

export type RoomsSendRoomMessageResponse = RoomsSendRoomMessageResponses[keyof RoomsSendRoomMessageResponses];
