// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://10.144.1.101:8213' | (string & {});
};

/**
 * Body_auth-upload_avatar
 */
export type BodyAuthUploadAvatar = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_scenarios-upload_scenario_document
 */
export type BodyScenariosUploadScenarioDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CharacterDetailResponse
 */
export type CharacterDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Name
     */
    name: string;
    game_system: GameSystem;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Data
     */
    data?: CoCCharacterDataOutput | {
        [key: string]: unknown;
    } | null;
};

/**
 * CharacterResponse
 */
export type CharacterResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Name
     */
    name: string;
    game_system: GameSystem;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CharacterSkill
 */
export type CharacterSkillInput = {
    type: CoCSkillType;
    category: CoCSkillCategory;
    /**
     * Name
     */
    name: string;
    /**
     * Base Value
     */
    base_value?: number;
    /**
     * Occupation Value
     */
    occupation_value?: number | null;
    /**
     * Interest Value
     */
    interest_value?: number | null;
    /**
     * Adjustments
     */
    adjustments?: Array<SkillAdjustment>;
};

/**
 * CharacterSkill
 */
export type CharacterSkillOutput = {
    type: CoCSkillType;
    category: CoCSkillCategory;
    /**
     * Name
     */
    name: string;
    /**
     * Base Value
     */
    base_value?: number;
    /**
     * Occupation Value
     */
    occupation_value?: number | null;
    /**
     * Interest Value
     */
    interest_value?: number | null;
    /**
     * Adjustments
     */
    adjustments?: Array<SkillAdjustment>;
    /**
     * Total Value
     */
    readonly total_value: number;
};

/**
 * ChunkExtractionResult
 */
export type ChunkExtractionResult = {
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Entities
     */
    entities: Array<ExtractedEntityResult>;
    /**
     * Relationships
     */
    relationships: Array<ExtractedRelationshipResult>;
};

/**
 * ChunkItemResult
 */
export type ChunkItemResult = {
    /**
     * Index
     */
    index: number;
    /**
     * Start Token
     */
    start_token: number;
    /**
     * End Token
     */
    end_token: number;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Text
     */
    text: string;
};

/**
 * ChunkResponse
 */
export type ChunkResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Start Token
     */
    start_token: number;
    /**
     * End Token
     */
    end_token: number;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Index
     */
    index: number;
};

/**
 * ChunkStepResponse
 */
export type ChunkStepResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: ProcessingStepStatus;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: 'chunk';
    result?: ChunkStepResult | null;
};

/**
 * ChunkStepResult
 */
export type ChunkStepResult = {
    /**
     * Chunk Size
     */
    chunk_size: number;
    /**
     * Overlap
     */
    overlap: number;
    /**
     * Total Tokens
     */
    total_tokens: number;
    /**
     * Chunks
     */
    chunks: Array<ChunkItemResult>;
};

/**
 * ChunkTextRequest
 */
export type ChunkTextRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Chunk Size
     */
    chunk_size?: number;
    /**
     * Overlap
     */
    overlap?: number;
};

/**
 * ChunkTextResponse
 */
export type ChunkTextResponse = {
    /**
     * Chunks
     */
    chunks: Array<ChunkResponse>;
};

/**
 * ClearGraphStepResponse
 */
export type ClearGraphStepResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: ProcessingStepStatus;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: 'clear_graph';
    result?: ClearGraphStepResult | null;
};

/**
 * ClearGraphStepResult
 */
export type ClearGraphStepResult = {
    /**
     * Chunks Deleted
     */
    chunks_deleted: number;
    /**
     * Legacy Chunks Deleted
     */
    legacy_chunks_deleted: number;
    /**
     * Orphan Entities Deleted
     */
    orphan_entities_deleted: number;
};

/**
 * CoCCharacterData
 *
 * COC 7th Edition 角色資料（存入 JSONB）
 */
export type CoCCharacterDataInput = {
    /**
     * Occupation
     */
    occupation?: string;
    occupational_features?: OccupationFeatureType;
    /**
     * Age
     */
    age?: number;
    /**
     * Gender
     */
    gender?: string;
    /**
     * Residence
     */
    residence?: string;
    /**
     * Birthplace
     */
    birthplace?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Hp
     */
    hp?: number;
    /**
     * Mp
     */
    mp?: number;
    /**
     * San
     */
    san?: number;
    /**
     * Luck
     */
    luck?: number;
    /**
     * Strength
     */
    strength?: number;
    /**
     * Constitution
     */
    constitution?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Dexterity
     */
    dexterity?: number;
    /**
     * Appearance
     */
    appearance?: number;
    /**
     * Intelligence
     */
    intelligence?: number;
    /**
     * Power
     */
    power?: number;
    /**
     * Education
     */
    education?: number;
    /**
     * Believer
     */
    believer?: boolean;
    /**
     * Cthulhu Mythos
     */
    cthulhu_mythos?: number;
    /**
     * Ideology Beliefs
     */
    ideology_beliefs?: string;
    /**
     * Significant People
     */
    significant_people?: string;
    /**
     * Meaningful Locations
     */
    meaningful_locations?: string;
    /**
     * Treasured Possessions
     */
    treasured_possessions?: string;
    /**
     * Traits
     */
    traits?: string;
    /**
     * Bonds
     */
    bonds?: string;
    /**
     * Skills
     */
    skills?: Array<CharacterSkillInput>;
};

/**
 * CoCCharacterData
 *
 * COC 7th Edition 角色資料（存入 JSONB）
 */
export type CoCCharacterDataOutput = {
    /**
     * Occupation
     */
    occupation?: string;
    occupational_features?: OccupationFeatureType;
    /**
     * Age
     */
    age?: number;
    /**
     * Gender
     */
    gender?: string;
    /**
     * Residence
     */
    residence?: string;
    /**
     * Birthplace
     */
    birthplace?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Hp
     */
    hp?: number;
    /**
     * Mp
     */
    mp?: number;
    /**
     * San
     */
    san?: number;
    /**
     * Luck
     */
    luck?: number;
    /**
     * Strength
     */
    strength?: number;
    /**
     * Constitution
     */
    constitution?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Dexterity
     */
    dexterity?: number;
    /**
     * Appearance
     */
    appearance?: number;
    /**
     * Intelligence
     */
    intelligence?: number;
    /**
     * Power
     */
    power?: number;
    /**
     * Education
     */
    education?: number;
    /**
     * Believer
     */
    believer?: boolean;
    /**
     * Cthulhu Mythos
     */
    cthulhu_mythos?: number;
    /**
     * Ideology Beliefs
     */
    ideology_beliefs?: string;
    /**
     * Significant People
     */
    significant_people?: string;
    /**
     * Meaningful Locations
     */
    meaningful_locations?: string;
    /**
     * Treasured Possessions
     */
    treasured_possessions?: string;
    /**
     * Traits
     */
    traits?: string;
    /**
     * Bonds
     */
    bonds?: string;
    /**
     * Skills
     */
    skills?: Array<CharacterSkillOutput>;
};

/**
 * CoCSkillAdjustmentType
 *
 * COC 技能調整來源
 */
export type CoCSkillAdjustmentType = 'GROWTH' | 'CUSTOM';

/**
 * CoCSkillCategory
 *
 * COC 技能分類
 */
export type CoCSkillCategory = 'NEGOTIATION' | 'INVESTIGATION' | 'LANGUAGE' | 'MEDICAL' | 'PILOT' | 'SURVIVAL' | 'ART_AND_CRAFT' | 'SCIENCE' | 'MOVEMENT' | 'COMBAT' | 'OCCUPATION' | 'CUSTOM';

/**
 * CoCSkillType
 *
 * COC 技能類型
 */
export type CoCSkillType = 'STANDARD' | 'DERIVED' | 'CUSTOM';

/**
 * CreateCharacterRequest
 */
export type CreateCharacterRequest = {
    /**
     * Name
     */
    name: string;
    game_system?: GameSystem;
};

/**
 * CreateRoomParticipantResponse
 */
export type CreateRoomParticipantResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Is Ready
     */
    is_ready: boolean;
    /**
     * Joined At
     */
    joined_at: string;
};

/**
 * CreateRoomRequest
 */
export type CreateRoomRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CreateRoomResponse
 */
export type CreateRoomResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Host Id
     */
    host_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    status: RoomStatus;
    /**
     * Invite Code
     */
    invite_code: string;
    /**
     * Participants
     */
    participants: Array<CreateRoomParticipantResponse>;
};

/**
 * CreateScenarioRequest
 */
export type CreateScenarioRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System
     *
     * COC, DND, etc.
     */
    system: string;
    /**
     * Min Players
     */
    min_players?: number | null;
    /**
     * Max Players
     */
    max_players?: number | null;
    /**
     * Min Hours
     */
    min_hours?: number | null;
    /**
     * Max Hours
     */
    max_hours?: number | null;
};

/**
 * DocumentMarkdownResponse
 */
export type DocumentMarkdownResponse = {
    /**
     * Content
     */
    content: string;
};

/**
 * DocumentProcessingLlmCallResponse
 */
export type DocumentProcessingLlmCallResponse = {
    /**
     * Id
     */
    id: string;
    step_id: ProcessingStepId;
    /**
     * Call Key
     */
    call_key: string;
    /**
     * Label
     */
    label: string;
    /**
     * Model
     */
    model: string;
    /**
     * Request
     */
    request: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Response
     */
    response: {
        [key: string]: unknown;
    } | string;
    /**
     * Sequence
     */
    sequence: number;
};

/**
 * DocumentProcessingPipelineResponse
 */
export type DocumentProcessingPipelineResponse = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Total Duration Ms
     */
    total_duration_ms: number | null;
    /**
     * Steps
     */
    steps: Array<({
        id: 'prepare';
    } & PrepareStepResponse) | ({
        id: 'clear_graph';
    } & ClearGraphStepResponse) | ({
        id: 'chunk';
    } & ChunkStepResponse) | ({
        id: 'entity_extraction';
    } & EntityExtractionStepResponse) | ({
        id: 'graph_build';
    } & GraphBuildStepResponse) | ({
        id: 'entity_embedding';
    } & EntityEmbeddingStepResponse) | ({
        id: 'entity_grouping';
    } & EntityGroupingStepResponse)>;
    /**
     * Llm Calls
     */
    llm_calls?: Array<DocumentProcessingLlmCallResponse>;
};

/**
 * DocumentResponse
 */
export type DocumentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Md Path
     */
    md_path: string | null;
    status: DocumentStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DocumentStatus
 */
export type DocumentStatus = 'READY' | 'PROCESSING' | 'COMPLETED' | 'FAILED';

/**
 * EntityEmbeddingStepResponse
 */
export type EntityEmbeddingStepResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: ProcessingStepStatus;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: 'entity_embedding';
    result?: EntityEmbeddingStepResult | null;
};

/**
 * EntityEmbeddingStepResult
 */
export type EntityEmbeddingStepResult = {
    /**
     * Model Key
     */
    model_key: string;
    /**
     * Entities Embedded
     */
    entities_embedded: number;
    /**
     * Cache Hits
     */
    cache_hits: number;
    /**
     * Cache Misses
     */
    cache_misses: number;
    /**
     * Similarity Edges Created
     */
    similarity_edges_created: number;
};

/**
 * EntityExtractionStepResponse
 */
export type EntityExtractionStepResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: ProcessingStepStatus;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: 'entity_extraction';
    result?: EntityExtractionStepResult | null;
};

/**
 * EntityExtractionStepResult
 */
export type EntityExtractionStepResult = {
    /**
     * Model
     */
    model: string;
    /**
     * Chunk Results
     */
    chunk_results: Array<ChunkExtractionResult>;
    /**
     * Total Entities
     */
    total_entities: number;
    /**
     * Total Relationships
     */
    total_relationships: number;
};

/**
 * EntityGroupChunk
 */
export type EntityGroupChunk = {
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Content
     */
    content: string;
};

/**
 * EntityGroupEntity
 */
export type EntityGroupEntity = {
    /**
     * Entity Id
     */
    entity_id: string;
    /**
     * Chunk Id
     */
    chunk_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * EntityGroupRequest
 */
export type EntityGroupRequest = {
    /**
     * Chunks
     */
    chunks: Array<EntityGroupChunk>;
    /**
     * Entities
     */
    entities: Array<EntityGroupEntity>;
};

/**
 * EntityGroupingInputChunkResult
 */
export type EntityGroupingInputChunkResult = {
    /**
     * Temp Id
     */
    temp_id: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Content
     */
    content: string;
};

/**
 * EntityGroupingInputEntityResult
 */
export type EntityGroupingInputEntityResult = {
    /**
     * Temp Id
     */
    temp_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Description
     */
    description: string;
};

/**
 * EntityGroupingIterationResult
 */
export type EntityGroupingIterationResult = {
    /**
     * Iteration
     */
    iteration: number;
    /**
     * Seed Name
     */
    seed_name: string;
    /**
     * Seed Similarity Degree
     */
    seed_similarity_degree: number;
    /**
     * Input Entities
     */
    input_entities: Array<EntityGroupingInputEntityResult>;
    /**
     * Input Chunks
     */
    input_chunks: Array<EntityGroupingInputChunkResult>;
    /**
     * Llm Groups
     */
    llm_groups: Array<Array<string>>;
    /**
     * Merges
     */
    merges: Array<EntityGroupingMergeRecord>;
};

/**
 * EntityGroupingMergeRecord
 */
export type EntityGroupingMergeRecord = {
    /**
     * Target Name
     */
    target_name: string;
    /**
     * Source Name
     */
    source_name: string;
    /**
     * Source Chunk Index
     */
    source_chunk_index: number;
    /**
     * Source Description
     */
    source_description: string;
    /**
     * Aliases Added
     */
    aliases_added: Array<string>;
};

/**
 * EntityGroupingStepResponse
 */
export type EntityGroupingStepResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: ProcessingStepStatus;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: 'entity_grouping';
    result?: EntityGroupingStepResult | null;
};

/**
 * EntityGroupingStepResult
 */
export type EntityGroupingStepResult = {
    /**
     * Total Iterations
     */
    total_iterations: number;
    /**
     * Total Merges
     */
    total_merges: number;
    /**
     * Iterations
     */
    iterations: Array<EntityGroupingIterationResult>;
};

/**
 * ExtractedEntityResult
 */
export type ExtractedEntityResult = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ExtractedRelationshipResult
 */
export type ExtractedRelationshipResult = {
    /**
     * Source Name
     */
    source_name: string;
    /**
     * Target Name
     */
    target_name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description: string;
};

/**
 * GameSystem
 */
export type GameSystem = 'COC' | 'DND';

/**
 * GraphBuildStepResponse
 */
export type GraphBuildStepResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: ProcessingStepStatus;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: 'graph_build';
    result?: GraphBuildStepResult | null;
};

/**
 * GraphBuildStepResult
 */
export type GraphBuildStepResult = {
    /**
     * Chunks Created
     */
    chunks_created: number;
    /**
     * Entities Created
     */
    entities_created: number;
    /**
     * Entities Merged
     */
    entities_merged: number;
    /**
     * Relationships Created
     */
    relationships_created: number;
    /**
     * Nodes
     */
    nodes: Array<GraphNodeCreatedResult>;
    /**
     * Edges
     */
    edges: Array<GraphEdgeCreatedResult>;
};

/**
 * GraphEdgeCreatedResult
 */
export type GraphEdgeCreatedResult = {
    /**
     * Id
     */
    id: string;
    /**
     * Source Name
     */
    source_name: string;
    /**
     * Target Name
     */
    target_name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description: string;
};

/**
 * GraphEntityType
 */
export type GraphEntityType = 'CHUNK' | 'LOCATION' | 'CHARACTER' | 'FACTION' | 'EVENT' | 'ITEM' | 'SAN_CHECK';

/**
 * GraphNodeCreatedResult
 */
export type GraphNodeCreatedResult = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description: string;
    /**
     * Source Chunk Index
     */
    source_chunk_index: number;
};

/**
 * GraphRelationshipType
 */
export type GraphRelationshipType = 'MENTIONS' | 'RELATES_TO' | 'SIMILAR_TO';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JoinRoomRequest
 */
export type JoinRoomRequest = {
    /**
     * Invite Code
     */
    invite_code: string;
};

/**
 * LlmCallResponse
 */
export type LlmCallResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Call Key
     */
    call_key: string;
    /**
     * Label
     */
    label: string;
    /**
     * Model
     */
    model: string;
    /**
     * Request
     */
    request: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Response
     */
    response: {
        [key: string]: unknown;
    } | string;
    /**
     * Sequence
     */
    sequence: number;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MeResponse
 */
export type MeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * OccupationFeatureType
 *
 * COC 職業技能點計算方式
 */
export type OccupationFeatureType = 'EDU' | 'EDU_STR' | 'EDU_DEX' | 'EDU_APP' | 'EDU_POW';

/**
 * PrepareStepResponse
 */
export type PrepareStepResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    status: ProcessingStepStatus;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: 'prepare';
    result?: PrepareStepResult | null;
};

/**
 * PrepareStepResult
 */
export type PrepareStepResult = {
    /**
     * Md Path
     */
    md_path: string;
    /**
     * Character Count
     */
    character_count: number;
    /**
     * Line Count
     */
    line_count: number;
    /**
     * Preview
     */
    preview: string;
};

/**
 * ProcessDocumentResponse
 */
export type ProcessDocumentResponse = {
    /**
     * Document Id
     */
    document_id: string;
    status: DocumentStatus;
    /**
     * Message
     */
    message: string;
    /**
     * Entities
     */
    entities: Array<unknown>;
    /**
     * Relationships
     */
    relationships: Array<unknown>;
};

/**
 * ProcessingStepId
 */
export type ProcessingStepId = 'prepare' | 'clear_graph' | 'chunk' | 'entity_extraction' | 'graph_build' | 'entity_embedding' | 'entity_grouping';

/**
 * ProcessingStepStatus
 */
export type ProcessingStepStatus = 'pending' | 'running' | 'completed' | 'failed' | 'skipped';

/**
 * RankedDocument
 */
export type RankedDocument = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Score
     */
    score: number;
    /**
     * Document
     */
    document: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RerankRequest
 */
export type RerankRequest = {
    /**
     * Query
     *
     * 查詢字串
     */
    query: string;
    /**
     * Documents
     *
     * 待排序的文件清單
     */
    documents: Array<string>;
};

/**
 * RerankResponse
 */
export type RerankResponse = {
    /**
     * Ranked Documents
     */
    ranked_documents: Array<RankedDocument>;
};

/**
 * RollDiceRequest
 */
export type RollDiceRequest = {
    /**
     * Count
     */
    count?: number;
    /**
     * Faces
     */
    faces?: number;
};

/**
 * RoomDetailResponse
 */
export type RoomDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Host Id
     */
    host_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    status: RoomStatus;
    /**
     * Invite Code
     */
    invite_code: string;
    /**
     * Participants
     */
    participants: Array<RoomParticipantResponse>;
};

/**
 * RoomMessageResponse
 */
export type RoomMessageResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Room Id
     */
    room_id: string;
    /**
     * Sender Id
     */
    sender_id: string | null;
    role: RoomMessageRole;
    type: RoomMessageType;
    /**
     * Content
     */
    content: string;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Llm Calls
     */
    llm_calls?: Array<LlmCallResponse>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RoomMessageRole
 */
export type RoomMessageRole = 'AGENT' | 'PLAYER' | 'SYSTEM';

/**
 * RoomMessageType
 */
export type RoomMessageType = 'CHAT' | 'DICE' | 'DEBUG';

/**
 * RoomParticipantResponse
 */
export type RoomParticipantResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * Is Ready
     */
    is_ready: boolean;
    /**
     * Joined At
     */
    joined_at: string;
    /**
     * Character Id
     */
    character_id?: string | null;
    /**
     * Character Name
     */
    character_name?: string | null;
};

/**
 * RoomResponse
 */
export type RoomResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Scenario Id
     */
    scenario_id: string;
    /**
     * Host Id
     */
    host_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    status: RoomStatus;
    /**
     * Invite Code
     */
    invite_code: string;
};

/**
 * RoomStatus
 */
export type RoomStatus = 'PREPARING' | 'RUNNING' | 'COMPLETED';

/**
 * ScenarioGraphEdgeResponse
 */
export type ScenarioGraphEdgeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Source
     */
    source: string;
    /**
     * Target
     */
    target: string;
    /**
     * Type
     */
    type?: GraphRelationshipType | string;
    /**
     * Directed
     */
    directed?: boolean;
};

/**
 * ScenarioGraphNodeResponse
 */
export type ScenarioGraphNodeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: GraphEntityType | string;
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Aliases
     */
    aliases?: Array<string>;
    /**
     * Descriptions
     */
    descriptions?: Array<string>;
};

/**
 * ScenarioGraphResponse
 */
export type ScenarioGraphResponse = {
    /**
     * Nodes
     */
    nodes: Array<ScenarioGraphNodeResponse>;
    /**
     * Edges
     */
    edges: Array<ScenarioGraphEdgeResponse>;
};

/**
 * ScenarioResponse
 */
export type ScenarioResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * System
     */
    system: string;
    /**
     * Min Players
     */
    min_players: number | null;
    /**
     * Max Players
     */
    max_players: number | null;
    /**
     * Min Hours
     */
    min_hours: number | null;
    /**
     * Max Hours
     */
    max_hours: number | null;
    /**
     * Creator Id
     */
    creator_id: string;
    status: ScenarioStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ScenarioStatus
 */
export type ScenarioStatus = 'DRAFT' | 'PUBLISHED';

/**
 * SelectCharacterRequest
 */
export type SelectCharacterRequest = {
    /**
     * Character Id
     */
    character_id?: string | null;
};

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * SkillAdjustment
 */
export type SkillAdjustment = {
    type: CoCSkillAdjustmentType;
    /**
     * Value
     */
    value: number;
    /**
     * Note
     */
    note?: string;
};

/**
 * SkillCheckRequest
 */
export type SkillCheckRequest = {
    /**
     * Skill Name
     */
    skill_name: string;
    /**
     * Skill Value
     */
    skill_value: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdateCharacterRequest
 */
export type UpdateCharacterRequest = {
    /**
     * Name
     */
    name?: string | null;
    data?: CoCCharacterDataInput | null;
};

/**
 * UpdateProfileRequest
 */
export type UpdateProfileRequest = {
    /**
     * Nickname
     */
    nickname?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * UpdateScenarioRequest
 */
export type UpdateScenarioRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System
     */
    system?: string | null;
    /**
     * Min Players
     */
    min_players?: number | null;
    /**
     * Max Players
     */
    max_players?: number | null;
    /**
     * Min Hours
     */
    min_hours?: number | null;
    /**
     * Max Hours
     */
    max_hours?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WsTicketResponse
 */
export type WsTicketResponse = {
    /**
     * Ticket
     */
    ticket: string;
    /**
     * Expires In Seconds
     */
    expires_in_seconds: number;
};

/**
 * CharacterDetailResponse
 */
export type CharacterDetailResponseWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Name
     */
    name: string;
    game_system: GameSystem;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Data
     */
    data?: CoCCharacterDataOutputWritable | {
        [key: string]: unknown;
    } | null;
};

/**
 * CharacterSkill
 */
export type CharacterSkillOutputWritable = {
    type: CoCSkillType;
    category: CoCSkillCategory;
    /**
     * Name
     */
    name: string;
    /**
     * Base Value
     */
    base_value?: number;
    /**
     * Occupation Value
     */
    occupation_value?: number | null;
    /**
     * Interest Value
     */
    interest_value?: number | null;
    /**
     * Adjustments
     */
    adjustments?: Array<SkillAdjustment>;
};

/**
 * CoCCharacterData
 *
 * COC 7th Edition 角色資料（存入 JSONB）
 */
export type CoCCharacterDataOutputWritable = {
    /**
     * Occupation
     */
    occupation?: string;
    occupational_features?: OccupationFeatureType;
    /**
     * Age
     */
    age?: number;
    /**
     * Gender
     */
    gender?: string;
    /**
     * Residence
     */
    residence?: string;
    /**
     * Birthplace
     */
    birthplace?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Hp
     */
    hp?: number;
    /**
     * Mp
     */
    mp?: number;
    /**
     * San
     */
    san?: number;
    /**
     * Luck
     */
    luck?: number;
    /**
     * Strength
     */
    strength?: number;
    /**
     * Constitution
     */
    constitution?: number;
    /**
     * Size
     */
    size?: number;
    /**
     * Dexterity
     */
    dexterity?: number;
    /**
     * Appearance
     */
    appearance?: number;
    /**
     * Intelligence
     */
    intelligence?: number;
    /**
     * Power
     */
    power?: number;
    /**
     * Education
     */
    education?: number;
    /**
     * Believer
     */
    believer?: boolean;
    /**
     * Cthulhu Mythos
     */
    cthulhu_mythos?: number;
    /**
     * Ideology Beliefs
     */
    ideology_beliefs?: string;
    /**
     * Significant People
     */
    significant_people?: string;
    /**
     * Meaningful Locations
     */
    meaningful_locations?: string;
    /**
     * Treasured Possessions
     */
    treasured_possessions?: string;
    /**
     * Traits
     */
    traits?: string;
    /**
     * Bonds
     */
    bonds?: string;
    /**
     * Skills
     */
    skills?: Array<CharacterSkillOutputWritable>;
};

export type WebsocketIssueWsTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/websocket/ticket';
};

export type WebsocketIssueWsTicketResponses = {
    /**
     * Successful Response
     */
    200: WsTicketResponse;
};

export type WebsocketIssueWsTicketResponse = WebsocketIssueWsTicketResponses[keyof WebsocketIssueWsTicketResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthUpdateMeData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthUpdateMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthUpdateMeError = AuthUpdateMeErrors[keyof AuthUpdateMeErrors];

export type AuthUpdateMeResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type AuthUpdateMeResponse = AuthUpdateMeResponses[keyof AuthUpdateMeResponses];

export type AuthUploadAvatarData = {
    body: BodyAuthUploadAvatar;
    path?: never;
    query?: never;
    url: '/auth/me/avatar';
};

export type AuthUploadAvatarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthUploadAvatarError = AuthUploadAvatarErrors[keyof AuthUploadAvatarErrors];

export type AuthUploadAvatarResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type AuthUploadAvatarResponse = AuthUploadAvatarResponses[keyof AuthUploadAvatarResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Response Auth-Logout
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type AuthRegisterResponse = AuthRegisterResponses[keyof AuthRegisterResponses];

export type MeListMyRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/rooms';
};

export type MeListMyRoomsResponses = {
    /**
     * Response Me-List My Rooms
     *
     * Successful Response
     */
    200: Array<RoomResponse>;
};

export type MeListMyRoomsResponse = MeListMyRoomsResponses[keyof MeListMyRoomsResponses];

export type UsersGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersGetAllResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersGetMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RerankerRerankEndpointData = {
    body: RerankRequest;
    path?: never;
    query?: never;
    url: '/reranker/rerank';
};

export type RerankerRerankEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RerankerRerankEndpointError = RerankerRerankEndpointErrors[keyof RerankerRerankEndpointErrors];

export type RerankerRerankEndpointResponses = {
    /**
     * Successful Response
     */
    200: RerankResponse;
};

export type RerankerRerankEndpointResponse = RerankerRerankEndpointResponses[keyof RerankerRerankEndpointResponses];

export type ScenariosListScenariosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/scenarios';
};

export type ScenariosListScenariosResponses = {
    /**
     * Response Scenarios-List Scenarios
     *
     * Successful Response
     */
    200: Array<ScenarioResponse>;
};

export type ScenariosListScenariosResponse = ScenariosListScenariosResponses[keyof ScenariosListScenariosResponses];

export type ScenariosCreateScenarioData = {
    body: CreateScenarioRequest;
    path?: never;
    query?: never;
    url: '/scenarios';
};

export type ScenariosCreateScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosCreateScenarioError = ScenariosCreateScenarioErrors[keyof ScenariosCreateScenarioErrors];

export type ScenariosCreateScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosCreateScenarioResponse = ScenariosCreateScenarioResponses[keyof ScenariosCreateScenarioResponses];

export type ScenariosGetScenarioData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}';
};

export type ScenariosGetScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosGetScenarioError = ScenariosGetScenarioErrors[keyof ScenariosGetScenarioErrors];

export type ScenariosGetScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosGetScenarioResponse = ScenariosGetScenarioResponses[keyof ScenariosGetScenarioResponses];

export type ScenariosUpdateScenarioData = {
    body: UpdateScenarioRequest;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}';
};

export type ScenariosUpdateScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosUpdateScenarioError = ScenariosUpdateScenarioErrors[keyof ScenariosUpdateScenarioErrors];

export type ScenariosUpdateScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosUpdateScenarioResponse = ScenariosUpdateScenarioResponses[keyof ScenariosUpdateScenarioResponses];

export type ScenariosPublishScenarioData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/publish';
};

export type ScenariosPublishScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosPublishScenarioError = ScenariosPublishScenarioErrors[keyof ScenariosPublishScenarioErrors];

export type ScenariosPublishScenarioResponses = {
    /**
     * Successful Response
     */
    200: ScenarioResponse;
};

export type ScenariosPublishScenarioResponse = ScenariosPublishScenarioResponses[keyof ScenariosPublishScenarioResponses];

export type ScenariosListScenarioDocumentsData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/documents';
};

export type ScenariosListScenarioDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosListScenarioDocumentsError = ScenariosListScenarioDocumentsErrors[keyof ScenariosListScenarioDocumentsErrors];

export type ScenariosListScenarioDocumentsResponses = {
    /**
     * Response Scenarios-List Scenario Documents
     *
     * Successful Response
     */
    200: Array<DocumentResponse>;
};

export type ScenariosListScenarioDocumentsResponse = ScenariosListScenarioDocumentsResponses[keyof ScenariosListScenarioDocumentsResponses];

export type ScenariosUploadScenarioDocumentData = {
    body: BodyScenariosUploadScenarioDocument;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/documents';
};

export type ScenariosUploadScenarioDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosUploadScenarioDocumentError = ScenariosUploadScenarioDocumentErrors[keyof ScenariosUploadScenarioDocumentErrors];

export type ScenariosUploadScenarioDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponse;
};

export type ScenariosUploadScenarioDocumentResponse = ScenariosUploadScenarioDocumentResponses[keyof ScenariosUploadScenarioDocumentResponses];

export type ScenariosCreateRoomData = {
    body: CreateRoomRequest;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/rooms';
};

export type ScenariosCreateRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosCreateRoomError = ScenariosCreateRoomErrors[keyof ScenariosCreateRoomErrors];

export type ScenariosCreateRoomResponses = {
    /**
     * Successful Response
     */
    200: CreateRoomResponse;
};

export type ScenariosCreateRoomResponse = ScenariosCreateRoomResponses[keyof ScenariosCreateRoomResponses];

export type ScenariosGetScenarioGraphData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: string;
    };
    query?: never;
    url: '/scenarios/{scenario_id}/graph';
};

export type ScenariosGetScenarioGraphErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScenariosGetScenarioGraphError = ScenariosGetScenarioGraphErrors[keyof ScenariosGetScenarioGraphErrors];

export type ScenariosGetScenarioGraphResponses = {
    /**
     * Successful Response
     */
    200: ScenarioGraphResponse;
};

export type ScenariosGetScenarioGraphResponse = ScenariosGetScenarioGraphResponses[keyof ScenariosGetScenarioGraphResponses];

export type DocumentsGetDocumentMarkdownData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/md';
};

export type DocumentsGetDocumentMarkdownErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentMarkdownError = DocumentsGetDocumentMarkdownErrors[keyof DocumentsGetDocumentMarkdownErrors];

export type DocumentsGetDocumentMarkdownResponses = {
    /**
     * Successful Response
     */
    200: DocumentMarkdownResponse;
};

export type DocumentsGetDocumentMarkdownResponse = DocumentsGetDocumentMarkdownResponses[keyof DocumentsGetDocumentMarkdownResponses];

export type DocumentsDownloadOriginalDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/download';
};

export type DocumentsDownloadOriginalDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDownloadOriginalDocumentError = DocumentsDownloadOriginalDocumentErrors[keyof DocumentsDownloadOriginalDocumentErrors];

export type DocumentsDownloadOriginalDocumentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsGetDocumentProcessingPipelineData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/processing-pipeline';
};

export type DocumentsGetDocumentProcessingPipelineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentProcessingPipelineError = DocumentsGetDocumentProcessingPipelineErrors[keyof DocumentsGetDocumentProcessingPipelineErrors];

export type DocumentsGetDocumentProcessingPipelineResponses = {
    /**
     * Successful Response
     */
    200: DocumentProcessingPipelineResponse;
};

export type DocumentsGetDocumentProcessingPipelineResponse = DocumentsGetDocumentProcessingPipelineResponses[keyof DocumentsGetDocumentProcessingPipelineResponses];

export type DocumentsProcessDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/process';
};

export type DocumentsProcessDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsProcessDocumentError = DocumentsProcessDocumentErrors[keyof DocumentsProcessDocumentErrors];

export type DocumentsProcessDocumentResponses = {
    /**
     * Successful Response
     */
    200: ProcessDocumentResponse;
};

export type DocumentsProcessDocumentResponse = DocumentsProcessDocumentResponses[keyof DocumentsProcessDocumentResponses];

export type DocumentsReprocessDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/reprocess';
};

export type DocumentsReprocessDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsReprocessDocumentError = DocumentsReprocessDocumentErrors[keyof DocumentsReprocessDocumentErrors];

export type DocumentsReprocessDocumentResponses = {
    /**
     * Successful Response
     */
    200: ProcessDocumentResponse;
};

export type DocumentsReprocessDocumentResponse = DocumentsReprocessDocumentResponses[keyof DocumentsReprocessDocumentResponses];

export type ToolsChunkPlainTextData = {
    body: ChunkTextRequest;
    path?: never;
    query?: never;
    url: '/tools/chunk-text';
};

export type ToolsChunkPlainTextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToolsChunkPlainTextError = ToolsChunkPlainTextErrors[keyof ToolsChunkPlainTextErrors];

export type ToolsChunkPlainTextResponses = {
    /**
     * Successful Response
     */
    200: ChunkTextResponse;
};

export type ToolsChunkPlainTextResponse = ToolsChunkPlainTextResponses[keyof ToolsChunkPlainTextResponses];

export type ToolsEntityExtractToolData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Text
         */
        text: string;
    };
    url: '/tools/entity-extract';
};

export type ToolsEntityExtractToolErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToolsEntityExtractToolError = ToolsEntityExtractToolErrors[keyof ToolsEntityExtractToolErrors];

export type ToolsEntityExtractToolResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ToolsEntityGroupToolData = {
    body: EntityGroupRequest;
    path?: never;
    query?: never;
    url: '/tools/entity-group';
};

export type ToolsEntityGroupToolErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToolsEntityGroupToolError = ToolsEntityGroupToolErrors[keyof ToolsEntityGroupToolErrors];

export type ToolsEntityGroupToolResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RoomsGetRoomData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}';
};

export type RoomsGetRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsGetRoomError = RoomsGetRoomErrors[keyof RoomsGetRoomErrors];

export type RoomsGetRoomResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsGetRoomResponse = RoomsGetRoomResponses[keyof RoomsGetRoomResponses];

export type RoomsJoinRoomData = {
    body: JoinRoomRequest;
    path?: never;
    query?: never;
    url: '/rooms/join';
};

export type RoomsJoinRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsJoinRoomError = RoomsJoinRoomErrors[keyof RoomsJoinRoomErrors];

export type RoomsJoinRoomResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsJoinRoomResponse = RoomsJoinRoomResponses[keyof RoomsJoinRoomResponses];

export type RoomsRegenerateInviteCodeData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/invite-code/regenerate';
};

export type RoomsRegenerateInviteCodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsRegenerateInviteCodeError = RoomsRegenerateInviteCodeErrors[keyof RoomsRegenerateInviteCodeErrors];

export type RoomsRegenerateInviteCodeResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsRegenerateInviteCodeResponse = RoomsRegenerateInviteCodeResponses[keyof RoomsRegenerateInviteCodeResponses];

export type RoomsKickParticipantData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/participants/{user_id}';
};

export type RoomsKickParticipantErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsKickParticipantError = RoomsKickParticipantErrors[keyof RoomsKickParticipantErrors];

export type RoomsKickParticipantResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsKickParticipantResponse = RoomsKickParticipantResponses[keyof RoomsKickParticipantResponses];

export type RoomsSelectCharacterData = {
    body: SelectCharacterRequest;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/character';
};

export type RoomsSelectCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsSelectCharacterError = RoomsSelectCharacterErrors[keyof RoomsSelectCharacterErrors];

export type RoomsSelectCharacterResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsSelectCharacterResponse = RoomsSelectCharacterResponses[keyof RoomsSelectCharacterResponses];

export type RoomsSetReadyData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query: {
        /**
         * Is Ready
         */
        is_ready: boolean;
    };
    url: '/rooms/{room_id}/ready';
};

export type RoomsSetReadyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsSetReadyError = RoomsSetReadyErrors[keyof RoomsSetReadyErrors];

export type RoomsSetReadyResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsSetReadyResponse = RoomsSetReadyResponses[keyof RoomsSetReadyResponses];

export type RoomsStartSessionData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/start';
};

export type RoomsStartSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsStartSessionError = RoomsStartSessionErrors[keyof RoomsStartSessionErrors];

export type RoomsStartSessionResponses = {
    /**
     * Successful Response
     */
    200: RoomDetailResponse;
};

export type RoomsStartSessionResponse = RoomsStartSessionResponses[keyof RoomsStartSessionResponses];

export type RoomsListRoomMessagesData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/messages';
};

export type RoomsListRoomMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsListRoomMessagesError = RoomsListRoomMessagesErrors[keyof RoomsListRoomMessagesErrors];

export type RoomsListRoomMessagesResponses = {
    /**
     * Response Rooms-List Room Messages
     *
     * Successful Response
     */
    200: Array<RoomMessageResponse>;
};

export type RoomsListRoomMessagesResponse = RoomsListRoomMessagesResponses[keyof RoomsListRoomMessagesResponses];

export type RoomsSendRoomMessageData = {
    body: SendMessageRequest;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/messages';
};

export type RoomsSendRoomMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsSendRoomMessageError = RoomsSendRoomMessageErrors[keyof RoomsSendRoomMessageErrors];

export type RoomsSendRoomMessageResponses = {
    /**
     * Successful Response
     */
    200: RoomMessageResponse;
};

export type RoomsSendRoomMessageResponse = RoomsSendRoomMessageResponses[keyof RoomsSendRoomMessageResponses];

export type RoomsRollDiceData = {
    body: RollDiceRequest;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/dice/roll';
};

export type RoomsRollDiceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsRollDiceError = RoomsRollDiceErrors[keyof RoomsRollDiceErrors];

export type RoomsRollDiceResponses = {
    /**
     * Successful Response
     */
    200: RoomMessageResponse;
};

export type RoomsRollDiceResponse = RoomsRollDiceResponses[keyof RoomsRollDiceResponses];

export type RoomsSkillCheckData = {
    body: SkillCheckRequest;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/rooms/{room_id}/dice/skill-check';
};

export type RoomsSkillCheckErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RoomsSkillCheckError = RoomsSkillCheckErrors[keyof RoomsSkillCheckErrors];

export type RoomsSkillCheckResponses = {
    /**
     * Successful Response
     */
    200: RoomMessageResponse;
};

export type RoomsSkillCheckResponse = RoomsSkillCheckResponses[keyof RoomsSkillCheckResponses];

export type CharactersListCharactersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/characters';
};

export type CharactersListCharactersResponses = {
    /**
     * Response Characters-List Characters
     *
     * Successful Response
     */
    200: Array<CharacterResponse>;
};

export type CharactersListCharactersResponse = CharactersListCharactersResponses[keyof CharactersListCharactersResponses];

export type CharactersCreateCharacterData = {
    body: CreateCharacterRequest;
    path?: never;
    query?: never;
    url: '/characters';
};

export type CharactersCreateCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersCreateCharacterError = CharactersCreateCharacterErrors[keyof CharactersCreateCharacterErrors];

export type CharactersCreateCharacterResponses = {
    /**
     * Successful Response
     */
    201: CharacterDetailResponse;
};

export type CharactersCreateCharacterResponse = CharactersCreateCharacterResponses[keyof CharactersCreateCharacterResponses];

export type CharactersDeleteCharacterData = {
    body?: never;
    path: {
        /**
         * Character Id
         */
        character_id: string;
    };
    query?: never;
    url: '/characters/{character_id}';
};

export type CharactersDeleteCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersDeleteCharacterError = CharactersDeleteCharacterErrors[keyof CharactersDeleteCharacterErrors];

export type CharactersDeleteCharacterResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CharactersDeleteCharacterResponse = CharactersDeleteCharacterResponses[keyof CharactersDeleteCharacterResponses];

export type CharactersGetCharacterData = {
    body?: never;
    path: {
        /**
         * Character Id
         */
        character_id: string;
    };
    query?: never;
    url: '/characters/{character_id}';
};

export type CharactersGetCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersGetCharacterError = CharactersGetCharacterErrors[keyof CharactersGetCharacterErrors];

export type CharactersGetCharacterResponses = {
    /**
     * Successful Response
     */
    200: CharacterDetailResponse;
};

export type CharactersGetCharacterResponse = CharactersGetCharacterResponses[keyof CharactersGetCharacterResponses];

export type CharactersUpdateCharacterData = {
    body: UpdateCharacterRequest;
    path: {
        /**
         * Character Id
         */
        character_id: string;
    };
    query?: never;
    url: '/characters/{character_id}';
};

export type CharactersUpdateCharacterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CharactersUpdateCharacterError = CharactersUpdateCharacterErrors[keyof CharactersUpdateCharacterErrors];

export type CharactersUpdateCharacterResponses = {
    /**
     * Successful Response
     */
    200: CharacterDetailResponse;
};

export type CharactersUpdateCharacterResponse = CharactersUpdateCharacterResponses[keyof CharactersUpdateCharacterResponses];
