import asyncio
import sys

sys.path.append(".")

from app.db.graph import neo4j_driver

data = {
    "document_id": "069e508b-2bec-70ce-8000-e6e7d71e2019",
    "message": "TODO: document processing not implemented",
    "entities": [
        {
            "name": "CJ",
            "type": "Character",
            "description": "敘述者／分享劇本心得的人，提到自己是帶過三次克蘇魯團的新米 keeper。",
        },
        {
            "name": "86式",
            "type": "Character",
            "description": "劇本《常暗之廂》的原作者。",
        },
        {
            "name": "常闇の箱",
            "type": "Document",
            "description": "劇本來源標示中的日文名稱，對應《常暗之廂》。",
        },
        {
            "name": "常暗之廂",
            "type": "Document",
            "description": "本次分享與翻譯的 TRPG 劇本名稱。",
        },
        {
            "name": "クトゥルフ神話TRPGやろうず シナリオ置き場",
            "type": "Organization",
            "description": "劇本來源網站／劇本置放處。",
        },
        {
            "name": "克蘇魯團",
            "type": "Other",
            "description": "CJ 提到自己帶過三次的克蘇魯 TRPG 團。",
        },
        {
            "name": "車廂",
            "type": "Location",
            "description": "劇本的重要舞台；文本提到劇本以車廂移動後不能返回為前提。",
        },
        {"name": "觀察", "type": "Other", "description": "推薦技能之一。"},
        {"name": "急救", "type": "Other", "description": "推薦技能之一。"},
        {"name": "說服", "type": "Other", "description": "推薦技能之一。"},
        {"name": "快速交談", "type": "Other", "description": "推薦技能之一。"},
        {"name": "潛行", "type": "Other", "description": "推薦技能之一。"},
        {
            "name": "幸運判定",
            "type": "Other",
            "description": "文本提到的判定；成功可保留持有物品，失敗則可能只剩衣服和眼鏡等。",
        },
        {
            "name": "可能只剩衣服和眼鏡",
            "type": "Resource",
            "description": "幸運判定失敗時，玩家可能只剩下的少量物品。",
        },
        {
            "name": "常闇の箱",
            "type": "Document",
            "description": "劇本的日文原名，與《常暗之廂》對應。",
        },
        {
            "name": "來不及返回的車廂移動",
            "type": "Event",
            "description": "劇本前提：車廂移動後無法返回。",
        },
        {
            "name": "末班電車",
            "type": "Location",
            "description": "探索者們搭乘的末班電車；在睡醒後仍持續奔走，窗外如同黑漆漆的隧道。",
        },
        {
            "name": "終點站",
            "type": "Location",
            "description": "電車原本的目的地；文本提到本應已到達的站點。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "開始地點；電車中的特定車廂。",
        },
        {
            "name": "車廂門扉上的紙條筆記",
            "type": "Document",
            "description": "貼在車廂門上的筆記，內容可見部分為「只管前進吧 已經…」。",
        },
        {
            "name": "探索者們",
            "type": "Character",
            "description": "搭乘末班電車的玩家角色群體；在車上睡著後醒來時發現其他乘客都不見了。",
        },
        {
            "name": "其他乘客",
            "type": "Character",
            "description": "與探索者們同乘的乘客；醒來時已全部消失。",
        },
        {
            "name": "幸運判定",
            "type": "Other",
            "description": "在6號車廂開始時要求全員進行的判定，用于決定所持物品的去留。",
        },
        {
            "name": "末班電車",
            "type": "Location",
            "description": "探索者們搭乘的末班電車；醒來後仍持續奔走，窗外如同黑漆漆的隧道。",
        },
        {
            "name": "終點站",
            "type": "Location",
            "description": "電車原本的目的地；文本提到本應已到達的站點。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "開始地點；電車中的特定車廂。",
        },
        {
            "name": "車廂門扉上的紙條筆記",
            "type": "Document",
            "description": "貼在車廂門上的筆記，內容可見部分為「只管前進吧 已經…」。",
        },
        {
            "name": "探索者們",
            "type": "Character",
            "description": "搭乘末班電車的玩家角色群體；在車上睡著後醒來時發現其他乘客都不見了。",
        },
        {
            "name": "其他乘客",
            "type": "Character",
            "description": "與探索者們同乘的乘客；醒來時已全部消失。",
        },
        {
            "name": "幸運判定",
            "type": "Other",
            "description": "在6號車廂開始時要求全員進行的判定，用于決定所持物品的去留。",
        },
        {
            "name": "紙條筆記",
            "type": "Document",
            "description": "貼在車廂門扉上的筆記，正面寫著「只管前進吧 已經沒有退路了」，背面寫著「第三個箱子裡有藏著鑰匙」。",
        },
        {
            "name": "第三個箱子裡有藏著鑰匙",
            "type": "Clue",
            "description": "紙條背面提供的線索，指出第3個車廂中藏有某個東西的鑰匙。",
        },
        {
            "name": "電車示意地圖",
            "type": "Document",
            "description": "貼在門扉旁邊的電車示意圖，經由《靈感》判定可得知7號車廂以後的部分被人蓄意塗掉。",
        },
        {
            "name": "7號車廂以後被塗掉的部分",
            "type": "Secret",
            "description": "電車示意地圖上，7號車廂之後的區域被人蓄意塗掉的隱藏資訊。",
        },
        {
            "name": "7號車廂",
            "type": "Location",
            "description": "電車中的一節車廂；前往此處需要進行《靈感》判定，並可能遭遇血腥屍體景象。",
        },
        {
            "name": "血腥臭味",
            "type": "Hazard",
            "description": "前往7號車廂時感知到的血腥氣味，暗示前方有可怕景象。",
        },
        {
            "name": "悲慘被撕裂的人體似的東西",
            "type": "Creature",
            "description": "在7號車廂中看到的散落一地的撕裂人體般的屍體／殘骸。",
        },
        {
            "name": "屍體",
            "type": "Other",
            "description": "在7號車廂中被《醫學》調查的 मृत者，醫學調查可知死亡時間不久。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "紙條筆記背面所指的車廂；線索稱第三個箱子裡藏有鑰匙，語境中「箱子」指的是車廂。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "藏在3號車廂中的某個東西的鑰匙。",
        },
        {
            "name": "蓄意塗掉的7號車廂以後區域",
            "type": "Secret",
            "description": "電車示意地圖上，7號車廂以後的部分被人刻意塗掉的事實。",
        },
        {
            "name": "被撕裂的人體似的東西",
            "type": "Event",
            "description": "7號車廂內出現的人體被撕裂般散落一地的景象，可視為屍體／殘骸的發現事件。",
        },
        {
            "name": "OO線電車",
            "type": "Location",
            "description": "報紙所提及、昨晚發生大規模恐怖事件的電車路線／電車事件相關對象。",
        },
        {
            "name": "7號車輛",
            "type": "Location",
            "description": "電車中的車輛；其深處有巨大類似嘴巴的東西正在啃蝕車廂。",
        },
        {
            "name": "8號車廂",
            "type": "Location",
            "description": "與7號車輛相鄰的車廂；原本應存在於7號車廂通往此處的門在失敗時不見了。",
        },
        {
            "name": "5號車廂",
            "type": "Location",
            "description": "場景所在車廂之一；在此可找到報紙，並發生有關6號車廂消失的靈感判定。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "被感知為已經有快要一半的部分要消失的車廂。",
        },
        {
            "name": "巨大類似嘴巴的東西",
            "type": "Creature",
            "description": "位於7號車輛深處、正在啃蝕車廂的巨大異常存在，推測比電車還要巨大。",
        },
        {
            "name": "明天的報紙",
            "type": "Item",
            "description": "在5號車廂找到的報紙；經判定可得知它記載的是同一年同一天的未來事件，因此可理解為來自明天的報紙。",
        },
        {
            "name": "昨晚OO線電車大規模的恐怖事件",
            "type": "Event",
            "description": "報紙內容所述事件；昨晚OO線電車發生的大規模恐怖事件，尚未被確認為恐怖分子所為。",
        },
        {
            "name": "倖存乘客的精神異常",
            "type": "Threat",
            "description": "報紙提到的後續異常狀態；倖存乘客全部被送往精神病院。",
        },
        {
            "name": "精神病院",
            "type": "Location",
            "description": "倖存乘客被送往的場所。",
        },
        {
            "name": "OO線電車",
            "type": "Location",
            "description": "報紙所提及、昨晚發生大規模恐怖事件的電車路線／事件相關對象。",
        },
        {
            "name": "7號車輛",
            "type": "Location",
            "description": "電車中的車輛；其深處有巨大類似嘴巴的東西正在啃蝕車廂。",
        },
        {
            "name": "8號車廂",
            "type": "Location",
            "description": "與7號車輛相鄰的車廂；原本應存在於7號車輛通往此處的門在失敗時不見了。",
        },
        {
            "name": "5號車廂",
            "type": "Location",
            "description": "場景所在車廂之一；在此可找到報紙，並發生有關6號車廂消失的靈感判定。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "被感知為已經有快要一半的部分要消失的車廂。",
        },
        {
            "name": "巨大類似嘴巴的東西",
            "type": "Creature",
            "description": "位於7號車輛深處、正在啃蝕車廂的巨大異常存在，推測比電車還要巨大。",
        },
        {
            "name": "報紙",
            "type": "Document",
            "description": "在5號車廂找到的報紙；內容記載昨晚OO線電車發生的大規模恐怖事件。",
        },
        {
            "name": "來自明天的報紙",
            "type": "Document",
            "description": "經查證後可知，該報紙上的事件與當年同月同日一致，因此被意識到是來自明天的報紙。",
        },
        {
            "name": "昨晚OO線電車大規模的恐怖事件",
            "type": "Event",
            "description": "報紙內容所述事件；昨晚OO線電車發生的大規模恐怖事件，尚未被確認為恐怖分子所為。",
        },
        {
            "name": "倖存乘客的精神異常",
            "type": "Threat",
            "description": "報紙提到的後續異常狀態；倖存乘客全部被送往精神病院。",
        },
        {
            "name": "精神病院",
            "type": "Location",
            "description": "倖存乘客被送往的場所。",
        },
        {
            "name": "4號車廂",
            "type": "Location",
            "description": "列車中的4號車廂，場景中可在此找到瀕死的乘務員。",
        },
        {
            "name": "5號車廂",
            "type": "Location",
            "description": "列車中的5號車廂，與超過行動限制時發出的異常聲響和腳下立足點消失的現象相關。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "在4號車廂被發現的瀕死乘務員；甦醒後會提供關於鑰匙與襲擊者的情報。",
        },
        {
            "name": "黑色包包",
            "type": "Item",
            "description": "乘務員原本隨身攜帶的黑色包包，鑰匙曾放在其中。",
        },
        {
            "name": "駕駛室房間鑰匙",
            "type": "Item",
            "description": "乘務員提到的鑰匙之一，原本在3號車廂，原文註記為KP可自行決定是否加入。",
        },
        {
            "name": "電車控制面板鑰匙",
            "type": "Item",
            "description": "乘務員明確提到的鑰匙，據稱原本放在黑色包包裡，後來掉在3號車廂前門附近。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "列車中的3號車廂；乘務員提到鑰匙掉落於前門附近，亦提及駕駛室房間鑰匙所在。",
        },
        {
            "name": "3號車廂的前門附近",
            "type": "Location",
            "description": "3號車廂內靠近前門的位置，乘務員表示鑰匙可能掉落於此。",
        },
        {
            "name": "人型的什麼",
            "type": "Creature",
            "description": "乘務員用來形容襲擊自己的不明人型存在，之後攻擊乘客並啃食他們。",
        },
        {
            "name": "乘客",
            "type": "Character",
            "description": "被不明人型存在襲擊並遭啃食的列車乘客。",
        },
        {
            "name": "乗務員",
            "type": "Character",
            "description": "4號車廂で発見される瀕死の乗務員。意識が戻ると、3號車廂の鍵の所在や襲撃者について話す。",
        },
        {
            "name": "3號車廂の前門附近",
            "type": "Location",
            "description": "3號車廂の前門付近。電車控制面板鑰匙が落ちている可能性がある場所として語られる。",
        },
        {
            "name": "車長室房間鑰匙",
            "type": "Item",
            "description": "乗務員が言及する鍵。原文では『駕駛室房間鑰匙』に相当し、KPが追加採用を選べるとある。",
        },
        {
            "name": "電車控制面板鑰匙",
            "type": "Item",
            "description": "乗務員が所持していた、あるいは失った鍵。黒色包包に入っていたが、逃走中に3號車廂の前門附近へ落ちたとされる。",
        },
        {
            "name": "黑色包包",
            "type": "Item",
            "description": "乗務員の身につけていた黒いバッグ。電車控制面板鑰匙が入っていた。",
        },
        {
            "name": "人型的什麼",
            "type": "Creature",
            "description": "乗務員を襲ったとされる正体不明の人型存在。乗客を次々に襲い、噛み食っていた。",
        },
        {
            "name": "乘客",
            "type": "Character",
            "description": "人型の存在に襲撃・捕食された列車の乗客。",
        },
        {
            "name": "4號車廂",
            "type": "Location",
            "description": "瀕死の乗務員が発見される車両。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "鍵の所在が示唆される車両。前門附近に落ちた可能性がある。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "電車上的乘務員，遭到襲擊後腿部受傷，請求玩家停下電車並幫助他逃跑；加入探索者隊伍。",
        },
        {
            "name": "襲擊者",
            "type": "Creature",
            "description": "大概是人型的存在，會襲擊乘客、咬人並像野獸般啃食；對聲音似乎很敏感，眼睛不是人類的。",
        },
        {
            "name": "探索者隊伍",
            "type": "Organization",
            "description": "玩家一行所屬的探索隊伍。",
        },
        {
            "name": "電車",
            "type": "Location",
            "description": "故事發生的移動載具；乘務員要求將其停下來以便逃跑。",
        },
        {
            "name": "乘客",
            "type": "Other",
            "description": "電車上的一般乘客，遭到襲擊者逐一咬食。",
        },
        {
            "name": "咬痕",
            "type": "Clue",
            "description": "乘務員腿部的咬傷痕跡，讓襲擊故事顯得更具現實感。",
        },
        {
            "name": "聲響",
            "type": "Clue",
            "description": "乘務員提到可用大聲響吸引襲擊者注意，例如把行李扔向牆壁製造噪音。",
        },
        {
            "name": "行李",
            "type": "Item",
            "description": "可被扔向牆壁製造聲響，用來吸引襲擊者注意的物品。",
        },
        {
            "name": "牆壁",
            "type": "Building",
            "description": "乘務員提到將行李扔向的表面，用以製造大聲響。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "電車中的一節車廂；若把乘務員放置在此處，他會被黑暗吞噬。",
        },
        {
            "name": "黑暗吞噬",
            "type": "Threat",
            "description": "發生在前往3號車廂時的威脅，會吞噬被放置在那裡的乘務員。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "在探索過程中需要尋找的關鍵物品；若帶著乘務員一起行動，尋找鑰匙會自動成功。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "電車上的乘務員，遭到襲擊後腿部受傷，請求玩家停下電車並幫助他逃跑；加入探索者隊伍。",
        },
        {
            "name": "襲擊者",
            "type": "Creature",
            "description": "大概是人型的存在，會襲擊乘客、咬人並像野獸般啃食；對聲音似乎很敏感，眼睛不是人類的。",
        },
        {
            "name": "探索者隊伍",
            "type": "Organization",
            "description": "玩家一行所屬的探索隊伍。",
        },
        {
            "name": "電車",
            "type": "Location",
            "description": "故事發生的移動載具；乘務員要求將其停下來以便逃跑。",
        },
        {
            "name": "乘客",
            "type": "Other",
            "description": "電車上的一般乘客，遭到襲擊者逐一咬食。",
        },
        {
            "name": "咬痕",
            "type": "Clue",
            "description": "乘務員腿部的咬傷痕跡，讓襲擊故事顯得更具現實感。",
        },
        {
            "name": "聲響",
            "type": "Clue",
            "description": "乘務員提到可用大聲響吸引襲擊者注意，例如把行李扔向牆壁製造噪音。",
        },
        {
            "name": "行李",
            "type": "Item",
            "description": "可被扔向牆壁製造聲響，用來吸引襲擊者注意的物品。",
        },
        {
            "name": "牆壁",
            "type": "Building",
            "description": "乘務員提到將行李扔向的表面，用以製造大聲響。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "電車中的一節車廂；若把乘務員放置在此處，他會被黑暗吞噬。",
        },
        {
            "name": "黑暗吞噬",
            "type": "Threat",
            "description": "發生在前往3號車廂時的威脅，會吞噬被放置在那裡的乘務員。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "在探索過程中需要尋找的關鍵物品；若帶著乘務員一起行動，尋找鑰匙會自動成功。",
        },
        {
            "name": "法行走",
            "type": "Other",
            "description": "章节/段落标题，表示这一段场景或规则说明的名称。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "场景中出现的乘务员，可随队前往3号车厢并参与寻找钥匙或补偿遗失物品。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "列车上的3号车厢，行李散落，可能用于寻找钥匙或遗失物品。",
        },
        {
            "name": "2號車廂",
            "type": "Location",
            "description": "列车上的2号车厢，从此处望去一片漆黑，看不见内部。",
        },
        {
            "name": "黑暗",
            "type": "Hazard",
            "description": "前往3号车厢时若将乘务员放置在那边，乘务员会被黑暗吞噬。",
        },
        {
            "name": "怪物",
            "type": "Creature",
            "description": "3号车厢内被观察判定为没有怪物存在。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "在3号车厢中需要寻找的重要物品，可由乘务员持有或由探索者取得。",
        },
        {
            "name": "隨身物品",
            "type": "Item",
            "description": "玩家之前弄丢的随身携带物品，可能在3号车厢中找回。",
        },
        {
            "name": "隨身攜帶包",
            "type": "Item",
            "description": "成功寻找随身物品时可找回的个人携带包。",
        },
        {
            "name": "打火機",
            "type": "Item",
            "description": "用于照明以查看2号车厢内部的工具。",
        },
        {
            "name": "手電筒",
            "type": "Item",
            "description": "用于照明以查看2号车厢内部的工具。",
        },
        {
            "name": "觀察",
            "type": "Other",
            "description": "用于发现3号车厢是否有怪物、寻找钥匙以及询问后获得搜索补正的技能。",
        },
        {
            "name": "說服",
            "type": "Other",
            "description": "可用于说服乘务员让探索者拿钥匙的技能。",
        },
        {
            "name": "快速交談",
            "type": "Other",
            "description": "可用于说服乘务员让探索者拿钥匙的技能。",
        },
        {
            "name": "知識",
            "type": "Other",
            "description": "在未询问乘务员具体钥匙归属时，可用于判断钥匙相关信息的技能。",
        },
        {
            "name": "幸運",
            "type": "Other",
            "description": "用于找回遗失随身物品的判定。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "玩家角色/调查者，可能通过说服、快速交谈、知识或幸运进行相关判定。",
        },
        {
            "name": "法行走",
            "type": "Other",
            "description": "章节/段落标题，表示这一段场景或规则说明的名称。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "场景中出现的乘务员，可随队前往3号车厢并参与寻找钥匙或补偿遗失物品。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "列车上的3号车厢，行李散落，可能用于寻找钥匙或遗失物品。",
        },
        {
            "name": "2號車廂",
            "type": "Location",
            "description": "列车上的2号车厢，从此处望去一片漆黑，看不见内部。",
        },
        {
            "name": "黑暗",
            "type": "Hazard",
            "description": "前往3号车厢时若将乘务员放置在那边，乘务员会被黑暗吞噬。",
        },
        {
            "name": "怪物",
            "type": "Creature",
            "description": "3号车厢内被观察判定为没有怪物存在。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "在3号车厢中需要寻找的重要物品，可由乘务员持有或由探索者取得。",
        },
        {
            "name": "隨身物品",
            "type": "Item",
            "description": "玩家之前弄丢的随身携带物品，可能在3号车厢中找回。",
        },
        {
            "name": "隨身攜帶包",
            "type": "Item",
            "description": "成功寻找随身物品时可找回的个人携带包。",
        },
        {
            "name": "打火機",
            "type": "Item",
            "description": "用于照明以查看2号车厢内部的工具。",
        },
        {
            "name": "手電筒",
            "type": "Item",
            "description": "用于照明以查看2号车厢内部的工具。",
        },
        {
            "name": "觀察",
            "type": "Other",
            "description": "用于发现3号车厢是否有怪物、寻找钥匙以及询问后获得搜索补正的技能。",
        },
        {
            "name": "說服",
            "type": "Other",
            "description": "可用于说服乘务员让探索者拿钥匙的技能。",
        },
        {
            "name": "快速交談",
            "type": "Other",
            "description": "可用于说服乘务员让探索者拿钥匙的技能。",
        },
        {
            "name": "知識",
            "type": "Other",
            "description": "在未询问乘务员具体钥匙归属时，可用于判断钥匙相关信息的技能。",
        },
        {
            "name": "幸運",
            "type": "Other",
            "description": "用于找回遗失随身物品的判定。",
        },
        {
            "name": "2號車廂",
            "type": "Location",
            "description": "車廂場景，內部一片漆黑，探索時可聽到 clicker 的喘息聲。",
        },
        {
            "name": "clicker",
            "type": "Creature",
            "description": "出現在2號車廂的怪物，沒有視力，探索者可注意到其沒有眼睛（上半部頭顱）。",
        },
        {
            "name": "手電筒",
            "type": "Item",
            "description": "可作為2號車廂的光源，對《觀察》有加成。",
        },
        {
            "name": "智慧型手機",
            "type": "Item",
            "description": "可作為較小光源，對2號車廂的《觀察》有少量加成。",
        },
        {"name": "打火機", "type": "Item", "description": "可用作2號車廂的照明光源。"},
        {
            "name": "SAN減少",
            "type": "Threat",
            "description": "看到 clicker 的 PL 時會導致的理智損失效果。",
        },
        {
            "name": "被撕裂破碎的屍體和鮮血惡臭",
            "type": "Clue",
            "description": "在7號車廂看過時會影響對 clicker 的 SAN 檢定，作為一種已見過的恐怖景象/氣味線索。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "曾遭襲擊的乘務員，文本提到若要聽音辨位襲擊者需做好進行 SAN 值檢定的心理準備。",
        },
        {
            "name": "襲擊乘務員的怪物",
            "type": "Creature",
            "description": "以聽音辨位方式提到的、襲擊了乘務員的怪物，文本未確認是否與 clicker 為同一種。",
        },
        {
            "name": "clicker",
            "type": "Creature",
            "description": "出現在2號車廂的怪物，沒有視力，且沒有眼睛（上半部頭顱）。",
        },
        {
            "name": "2號車廂",
            "type": "Location",
            "description": "黑暗的車廂場景，clicker 出沒於此。",
        },
        {
            "name": "7號車廂",
            "type": "Location",
            "description": "提及可在此先見到被撕裂破碎的屍體與鮮血惡臭。",
        },
        {
            "name": "被撕裂破碎的屍體與鮮血惡臭",
            "type": "Clue",
            "description": "在7號車廂可見/可聞到的恐怖景象與氣味，會影響後續面對 clicker 時的 SAN 反應。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "提及曾遭某怪物襲擊的乘務員。",
        },
        {
            "name": "襲擊了乘務員的怪物",
            "type": "Creature",
            "description": "曾襲擊乘務員的怪物；文本未确认是否与 clicker 为同类。",
        },
        {"name": "打火機", "type": "Item", "description": "可用于照明的光源。"},
        {
            "name": "手電筒",
            "type": "Item",
            "description": "可用于照明，并对对2號車廂的《觀察》提供加成。",
        },
        {
            "name": "智慧型手機",
            "type": "Item",
            "description": "可作为较小光源，并对对2號車廂的《觀察》提供少量加成。",
        },
        {
            "name": "SAN減少",
            "type": "Threat",
            "description": "看到 clicker 或相关恐怖景象时会发生的理智损失效果。",
        },
        {
            "name": "clicker",
            "type": "Creature",
            "description": "在列車車廂中出現的敵對生物；會注意到聲音並追捕行動者，且數量達兩隻以上時會讓STR對抗自動失敗。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "在本段中被提及會因自動失敗而被抓住的乘務員；其擲骰過程被省略。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "進行潛行、投擲、幸運、DEX/STR對抗與可能戰鬥的角色群；其中有人可能在乘務員被抓走前取得鑰匙。",
        },
        {
            "name": "車廂",
            "type": "Location",
            "description": "發生潛行與遭遇clicker的列車車廂。",
        },
        {
            "name": "屍體",
            "type": "Other",
            "description": "腳下可能踩到的屍體；踩到時會發出聲響並引來clicker注意。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "可在乘務員被抓走之前取得的物品。",
        },
        {
            "name": "聲響",
            "type": "Clue",
            "description": "用丟擲隨身物品撞牆製造的聲音，可用來趁空檔溜走。",
        },
        {
            "name": "戰鬥",
            "type": "Event",
            "description": "若失敗後進入的對抗情境；文本明示基本上絕對打不贏。",
        },
        {
            "name": "clicker",
            "type": "Creature",
            "description": "在列車車廂中出現的敵對生物；會注意到聲音並追捕行動者，且數量達兩隻以上時會讓STR對抗自動失敗。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "在本段中被提及會因自動失敗而被抓住的乘務員；其擲骰過程被省略。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "進行潛行、投擲、幸運、DEX/STR對抗與可能戰鬥的角色群；其中有人可能在乘務員被抓走前取得鑰匙。",
        },
        {
            "name": "車廂",
            "type": "Location",
            "description": "發生潛行與遭遇clicker的列車車廂。",
        },
        {
            "name": "屍體",
            "type": "Other",
            "description": "腳下可能踩到的屍體；踩到時會發出聲響並引來clicker注意。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "可在乘務員被抓走之前取得的物品。",
        },
        {
            "name": "聲響",
            "type": "Clue",
            "description": "用丟擲隨身物品撞牆製造的聲音，可用來趁空檔溜走。",
        },
        {
            "name": "戰鬥",
            "type": "Event",
            "description": "若失敗後進入的對抗情境；文本明示基本上絕對打不贏。",
        },
        {
            "name": "先頭車廂",
            "type": "Location",
            "description": "電車的前方車廂，與二號車廂不同，環境安靜且普通。",
        },
        {
            "name": "二號車廂",
            "type": "Location",
            "description": "與先頭車廂對比提及的另一節車廂。",
        },
        {
            "name": "駕駛室",
            "type": "Room",
            "description": "需要使用鑰匙開門進入的電車駕駛空間。",
        },
        {
            "name": "操作面板",
            "type": "Item",
            "description": "駕駛室內可用鑰匙打開的控制面板。",
        },
        {
            "name": "控制拉桿",
            "type": "Item",
            "description": "操作面板上的控制裝置，包含左邊與右邊兩支拉桿。",
        },
        {
            "name": "左邊的拉桿",
            "type": "Item",
            "description": "控制拉桿之一，拉下時為煞車起步裝置。",
        },
        {
            "name": "右邊的拉桿",
            "type": "Item",
            "description": "控制拉桿之一，作為油門；往下拉可加速，往上拉可減速。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "用來打開駕駛室與操作面板的鑰匙；若先前取得駕駛室鑰匙，則需要它開門。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "電車乘務員；在場時會想直接把電車停下來。",
        },
        {
            "name": "電車",
            "type": "Other",
            "description": "本段場景中的交通載具，可由駕駛室與控制拉桿操作。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "進行探索與戰鬥的角色群；文本中作為技能檢定與受傷效果的對象。",
        },
        {
            "name": "說服",
            "type": "Other",
            "description": "可用來阻止或改變乘務員行動的社交行動或技能。",
        },
        {
            "name": "快速交談",
            "type": "Other",
            "description": "可用來阻止或改變乘務員行動的社交行動或技能。",
        },
        {
            "name": "STR對抗",
            "type": "Other",
            "description": "可用來阻止或改變乘務員行動的力量對抗。",
        },
        {
            "name": "戰鬥",
            "type": "Event",
            "description": "文本明示此處戰鬥幾乎絕對打不贏，且環境對戰鬥極為不利。",
        },
        {
            "name": "電車駕駛基本知識",
            "type": "Clue",
            "description": "詢問乘務員可得知的操作資訊，包含左桿煞車起步、右桿油門、下拉加速、上拉減速。",
        },
        {
            "name": "先頭車廂",
            "type": "Location",
            "description": "電車的前方車廂，與二號車廂不同，環境安靜且普通。",
        },
        {
            "name": "二號車廂",
            "type": "Location",
            "description": "與先頭車廂對比提及的另一節車廂。",
        },
        {
            "name": "駕駛室",
            "type": "Room",
            "description": "需要使用鑰匙開門進入的電車駕駛空間。",
        },
        {
            "name": "操作面板",
            "type": "Item",
            "description": "駕駛室內可用鑰匙打開的控制面板。",
        },
        {
            "name": "控制拉桿",
            "type": "Item",
            "description": "操作面板上的控制裝置，包含左邊與右邊兩支拉桿。",
        },
        {
            "name": "左邊的拉桿",
            "type": "Item",
            "description": "控制拉桿之一，拉下時為煞車起步裝置。",
        },
        {
            "name": "右邊的拉桿",
            "type": "Item",
            "description": "控制拉桿之一，作為油門；往下拉可加速，往上拉可減速。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "用來打開駕駛室與操作面板的鑰匙；若先前取得駕駛室鑰匙，則需要它開門。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "電車乘務員；在場時會想直接把電車停下來。",
        },
        {
            "name": "電車",
            "type": "Other",
            "description": "本段場景中的交通載具，可由駕駛室與控制拉桿操作。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "進行探索與戰鬥的角色群；文本中作為技能檢定與受傷效果的對象。",
        },
        {
            "name": "說服",
            "type": "Other",
            "description": "可用來阻止或改變乘務員行動的社交行動或技能。",
        },
        {
            "name": "快速交談",
            "type": "Other",
            "description": "可用來阻止或改變乘務員行動的社交行動或技能。",
        },
        {
            "name": "STR對抗",
            "type": "Other",
            "description": "可用來阻止或改變乘務員行動的力量對抗。",
        },
        {
            "name": "戰鬥",
            "type": "Event",
            "description": "文本明示此處戰鬥幾乎絕對打不贏，且環境對戰鬥極為不利。",
        },
        {
            "name": "電車駕駛基本知識",
            "type": "Clue",
            "description": "詢問乘務員可得知的操作資訊，包含左桿煞車起步、右桿油門、下拉加速、上拉減速。",
        },
        {
            "name": "電車",
            "type": "Location",
            "description": "故事中的主要移動場景，存在加速與減速兩種結局分歧；結局A中探索者回到睡著前的6號車廂並抵達熟悉的停靠站。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "電車上的特定車廂，結局A中探索者醒來時回到此處。",
        },
        {
            "name": "停靠站",
            "type": "Location",
            "description": "電車抵達的熟悉站點，結局A中作為返回現實的終點。",
        },
        {
            "name": "站務人員",
            "type": "Character",
            "description": "結局A中出現的人員，向探索者詢問是否沒事；若詢問乘務員NPC，站務員表示不認識或沒有這樣的人。",
        },
        {
            "name": "乘務員NPC",
            "type": "Character",
            "description": "被提及但在結局A中被站務員否認存在的乘務員角色。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "玩家角色群體，乘坐電車並可能透過加速或減速改變結局；若採用STR對抗乘務員時，受傷的探索者有+20%補正。",
        },
        {
            "name": "結局A",
            "type": "Event",
            "description": "加速路線的結局，標示為True End；探索者回到現實世界並離開電車返家。",
        },
        {
            "name": "結局B",
            "type": "Event",
            "description": "減速路線的結局，標示為BAD END；列車停下時出現咀嚼聲、屍塊、血水與鐵鏽味等恐怖景象。",
        },
        {"name": "True End", "type": "Event", "description": "結局A的標記。"},
        {"name": "BAD END", "type": "Event", "description": "結局B的標記。"},
        {
            "name": "加速",
            "type": "Other",
            "description": "玩家可採取的處置之一，用來改變劇情並導向結局A。",
        },
        {
            "name": "減速",
            "type": "Other",
            "description": "玩家可採取的處置之一，用來改變劇情並導向結局B。",
        },
        {
            "name": "趴哩啪哩的咀嚼聲",
            "type": "Clue",
            "description": "結局B中逐漸接近的咀嚼聲線索，對應恐怖場面與危險逼近。",
        },
        {
            "name": "嘓哩嘓哩的咀嚼音",
            "type": "Clue",
            "description": "結局B中提到的咀嚼聲描述，與趴哩啪哩的咀嚼聲同屬恐怖聲響線索。",
        },
        {
            "name": "殘缺腐爛的屍塊",
            "type": "Clue",
            "description": "結局B中列車停下後出現的恐怖景象之一。",
        },
        {
            "name": "血水",
            "type": "Clue",
            "description": "結局B中列車停下後出現的恐怖景象之一。",
        },
        {
            "name": "鐵鏽的味道",
            "type": "Clue",
            "description": "結局B中充滿的氣味線索，與恐怖場景相關。",
        },
        {
            "name": "現實世界",
            "type": "Location",
            "description": "結局A中被確認返回的現實層面。",
        },
        {
            "name": "黑色包",
            "type": "Item",
            "description": "一個背帶被切斷的黑色包，醒來後出現在探索者的所持物品中。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "車廂之一；理想流程中需要先確認黏在門上的筆記，且其消失與後續事件相關。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "被6號車廂筆記背面提及的車廂。",
        },
        {
            "name": "5號車廂",
            "type": "Location",
            "description": "理想流程中可在此看到報紙以掌握現在的狀況。",
        },
        {
            "name": "黏在門上的筆記",
            "type": "Document",
            "description": "黏在6號車廂門上的筆記，背面寫有關於3號車廂的事情。",
        },
        {
            "name": "報紙",
            "type": "Document",
            "description": "在5號車廂可看到的報紙，用來掌握當前狀況。",
        },
        {"name": "結局A", "type": "Event", "description": "達成後可領取報酬的結局。"},
        {
            "name": "生還",
            "type": "Resource",
            "description": "報酬的一部分，依生還人數不同而變動的SAN值回復。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "報酬結算時提及的角色類別；其生還數量影響SAN值回復。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "持有黑色包的角色集合或玩家角色，文本中以探索者指稱。",
        },
        {
            "name": "黑色包",
            "type": "Item",
            "description": "一個背帶被切斷的黑色包，醒來後出現在探索者的所持物品中。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "車廂之一；理想流程中需要先確認黏在門上的筆記，且其消失與後續事件相關。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "被6號車廂筆記背面提及的車廂。",
        },
        {
            "name": "5號車廂",
            "type": "Location",
            "description": "理想流程中可在此看到報紙以掌握現在的狀況。",
        },
        {
            "name": "黏在門上的筆記",
            "type": "Document",
            "description": "黏在6號車廂門上的筆記，背面寫有關於3號車廂的事情。",
        },
        {
            "name": "報紙",
            "type": "Document",
            "description": "在5號車廂可看到的報紙，用來掌握當前狀況。",
        },
        {"name": "結局A", "type": "Event", "description": "達成後可領取報酬的結局。"},
        {
            "name": "生還",
            "type": "Resource",
            "description": "報酬的一部分，依生還人數不同而變動的SAN值回復。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "報酬結算時提及的角色類別；其生還數量影響SAN值回復。",
        },
        {
            "name": "探索者",
            "type": "Character",
            "description": "持有黑色包的角色集合或玩家角色，文本中以探索者指稱。",
        },
        {
            "name": "3號車廂",
            "type": "Location",
            "description": "電車中的第3號車廂；背面有寫到相關事情，且在此找到鑰匙。",
        },
        {
            "name": "5號車廂",
            "type": "Location",
            "description": "電車中的第5號車廂；在此看到報紙並掌握了現在的狀況。",
        },
        {
            "name": "6號車廂",
            "type": "Location",
            "description": "電車中的第6號車廂；其消失被注意到，並且無法返回之前的車廂。",
        },
        {
            "name": "4號車廂",
            "type": "Location",
            "description": "電車中的第4號車廂；在此幫助了乘務員，並得知鑰匙所在地或選擇一起同行。",
        },
        {
            "name": "2號車廂",
            "type": "Location",
            "description": "電車中的第2號車廂；可不出聲音地溜過。",
        },
        {
            "name": "先頭車廂",
            "type": "Location",
            "description": "電車最前端的車廂；在此使用找到的鑰匙啟動控制面板，使電車達到最高速。",
        },
        {
            "name": "電車",
            "type": "Other",
            "description": "本劇情發生的移動載具；需要加速以逃出。",
        },
        {
            "name": "報紙",
            "type": "Document",
            "description": "在5號車廂看到的報紙，用來掌握當前狀況。",
        },
        {
            "name": "筆記",
            "type": "Document",
            "description": "先前留下的筆記，提示需要將電車加速。",
        },
        {
            "name": "鑰匙",
            "type": "Item",
            "description": "在3號車廂找到的關鍵物品；被用來啟動控制面板。",
        },
        {
            "name": "控制面板",
            "type": "Item",
            "description": "先頭車廂中的裝置；用找到的鑰匙啟動後可使電車達到最高速。",
        },
        {
            "name": "逃出",
            "type": "Objective",
            "description": "本段流程的最終目標：從電車與循聲者的威脅中逃離。",
        },
        {
            "name": "京山 人吉",
            "type": "Character",
            "description": "30歲男性乘務員；沒有惡意的神祕角色，受傷，想停下電車並從Clicker手中脫逃，不知道5-7號車廂的情報。",
        },
        {
            "name": "乘務員",
            "type": "Character",
            "description": "電車上的乘務員；其姓名為京山 人吉。",
        },
        {
            "name": "Clicker",
            "type": "Creature",
            "description": "敵方NPC，出典為《最後生還者》；沒有眼睛，對光源沒有任何反應，數量由GM決定。",
        },
        {
            "name": "循聲者",
            "type": "Creature",
            "description": "Clicker的中文稱呼；敵方NPC，沒有眼睛，對光源沒有任何反應。",
        },
        {
            "name": "京山 人吉",
            "type": "Character",
            "description": "30歲男性乘務員；沒有惡意的神祕角色，受傷，想停下電車並從Clicker手中脫逃，不知道5-7號車廂的情報。",
        },
        {
            "name": "Clicker",
            "type": "Creature",
            "description": "敵方NPC，出典為《最後生還者》；沒有眼睛，對光源沒有任何反應，數量由GM決定。",
        },
        {
            "name": "循聲者",
            "type": "Creature",
            "description": "Clicker的中文稱呼；敵方NPC，沒有眼睛，對光源沒有任何反應。",
        },
        {
            "name": "5-7號車廂",
            "type": "Location",
            "description": "乘務員不知道其相關情報的車廂範圍；原文提及5-7號車廂的情報。",
        },
        {
            "name": "現在的狀況",
            "type": "Other",
            "description": "玩家透過報紙得知的當前局勢。",
        },
        {"name": "消失", "type": "Event", "description": "6號車廂的消失事件。"},
        {
            "name": "無法返回之前的車廂",
            "type": "Threat",
            "description": "探索者們注意到的狀況：無法回到先前的車廂。",
        },
        {
            "name": "阿巴頓",
            "type": "Deity",
            "description": "被揭示為追逐電車的大嘴的真正身份，稱為深淵之王。",
        },
        {"name": "深淵之王", "type": "Deity", "description": "阿巴頓的稱號/身份。"},
        {
            "name": "追逐電車的大嘴",
            "type": "Creature",
            "description": "在劇本中追逐電車的敵對存在，其正體為阿巴頓。",
        },
        {
            "name": "敵方NPC",
            "type": "Creature",
            "description": "敵對NPC，沒有眼睛，對光源沒有反應，對聲音極度敏感；數量由GM以1d3決定。",
        },
        {
            "name": "光源",
            "type": "Item",
            "description": "可用來對付敵方NPC的光照來源。",
        },
        {
            "name": "投擲技能",
            "type": "Other",
            "description": "可用於丟東西製造聲響、配合潛行的技能。",
        },
        {
            "name": "返回的電車門",
            "type": "Location",
            "description": "被建議封死的電車返回方向的門。",
        },
        {
            "name": "電車",
            "type": "Location",
            "description": "被啃食、被追逐的交通載具；劇本事件發生的主要場景。",
        },
        {
            "name": "電車被啃食",
            "type": "Event",
            "description": "GM建議以聲響提醒探索者的事件。",
        },
        {"name": "END A", "type": "Other", "description": "劇本提及的結局A。"},
        {
            "name": "聲音",
            "type": "Other",
            "description": "敵方NPC極度敏感的刺激來源；用來製造聲響可幫助潛行。",
        },
        {
            "name": "光源",
            "type": "Item",
            "description": "敵方NPC對其沒有任何反應；失敗時GM可用光源消滅敵方NPC作為處罰。",
        },
    ],
    "relationships": [
        {
            "source_name": "CJ",
            "target_name": "常暗之廂",
            "type": "shares_scenario",
            "description": "CJ 正在分享這個劇本的翻譯與跑團心得。",
        },
        {
            "source_name": "常闇の箱",
            "target_name": "常暗之廂",
            "type": "same_as",
            "description": "日文劇本名對應中文劇本名。",
        },
        {
            "source_name": "86式",
            "target_name": "常闇の箱",
            "type": "created_by",
            "description": "86式 是劇本《常闇の箱》的原作者。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "クトゥルフ神話TRPGやろうず シナリオ置き場",
            "type": "originates_from",
            "description": "劇本來源標示為該劇本置放處。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "車廂",
            "type": "features_location",
            "description": "劇本以車廂為主要舞台。",
        },
        {
            "source_name": "車廂",
            "target_name": "不能返回",
            "type": "has_property",
            "description": "文本明示車廂移動後不能返回，是劇本前提。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "幸運判定",
            "type": "includes_element",
            "description": "劇本概要中提到持有物品與幸運判定的處理。",
        },
        {
            "source_name": "幸運判定",
            "target_name": "持有物品",
            "type": "affects",
            "description": "成功時持有物品會被保留，失敗時則可能只剩衣服和眼鏡等。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "觀察",
            "type": "recommends_skill",
            "description": "劇本推薦技能之一。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "急救",
            "type": "recommends_skill",
            "description": "劇本推薦技能之一。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "說服",
            "type": "recommends_skill",
            "description": "劇本推薦技能之一。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "快速交談",
            "type": "recommends_skill",
            "description": "劇本推薦技能之一。",
        },
        {
            "source_name": "常暗之廂",
            "target_name": "潛行",
            "type": "recommends_skill",
            "description": "劇本推薦技能之一。",
        },
        {
            "source_name": "CJ",
            "target_name": "克蘇魯團",
            "type": "has_experience_with",
            "description": "CJ 提到自己帶過三次克蘇魯團。",
        },
        {
            "source_name": "幸運判定",
            "target_name": "可能只剩衣服和眼鏡",
            "type": "results_in",
            "description": "失敗時只會剩下衣服和眼鏡之類的東西。",
        },
        {
            "source_name": "車廂",
            "target_name": "來不及返回的車廂移動",
            "type": "involved_in",
            "description": "劇本以車廂移動後不能返回為前提。",
        },
        {
            "source_name": "來不及返回的車廂移動",
            "target_name": "不能返回",
            "type": "has_property",
            "description": "該移動的結果是無法返回。",
        },
        {
            "source_name": "探索者們",
            "target_name": "末班電車",
            "type": "located_in",
            "description": "探索者們搭乘本日的末班電車。",
        },
        {
            "source_name": "末班電車",
            "target_name": "終點站",
            "type": "objective_targets",
            "description": "電車的目的地是終點站。",
        },
        {
            "source_name": "末班電車",
            "target_name": "終點站",
            "type": "located_in",
            "description": "文本指出電車本應已到達終點站，但仍在繼續奔走。",
        },
        {
            "source_name": "其他乘客",
            "target_name": "末班電車",
            "type": "located_in",
            "description": "其他乘客原本與探索者們同乘於電車上，醒來時已不見。",
        },
        {
            "source_name": "探索者們",
            "target_name": "其他乘客",
            "type": "not_with",
            "description": "探索者們醒來時，车上除了自己以外已沒有其他乘客。",
        },
        {
            "source_name": "末班電車",
            "target_name": "6號車廂",
            "type": "part_of",
            "description": "6號車廂是末班電車中的一節車廂。",
        },
        {
            "source_name": "車廂門扉上的紙條筆記",
            "target_name": "6號車廂",
            "type": "located_in",
            "description": "紙條筆記貼在6號車廂的車廂門扉上。",
        },
        {
            "source_name": "車廂門扉上的紙條筆記",
            "target_name": "前進",
            "type": "objective_targets",
            "description": "紙條內容要求只管前進。",
        },
        {
            "source_name": "幸運判定",
            "target_name": "探索者們",
            "type": "applies_to",
            "description": "在6號車廂開始地點，全員需要進行幸運判定。",
        },
        {
            "source_name": "幸運判定",
            "target_name": "所持物品",
            "type": "resource",
            "description": "判定用來決定身上的所持物品的去留。",
        },
        {
            "source_name": "探索者們",
            "target_name": "末班電車",
            "type": "located_in",
            "description": "探索者們搭乘本日的末班電車。",
        },
        {
            "source_name": "末班電車",
            "target_name": "終點站",
            "type": "objective_targets",
            "description": "電車的目的地是終點站。",
        },
        {
            "source_name": "末班電車",
            "target_name": "終點站",
            "type": "located_in",
            "description": "文本指出電車本應已到達終點站，但仍在繼續奔走。",
        },
        {
            "source_name": "其他乘客",
            "target_name": "末班電車",
            "type": "located_in",
            "description": "其他乘客原本與探索者們同乘於電車上，醒來時已不見。",
        },
        {
            "source_name": "探索者們",
            "target_name": "其他乘客",
            "type": "not_with",
            "description": "探索者們醒來時，車上除了自己以外已沒有其他乘客。",
        },
        {
            "source_name": "末班電車",
            "target_name": "6號車廂",
            "type": "part_of",
            "description": "6號車廂是末班電車中的一節車廂。",
        },
        {
            "source_name": "車廂門扉上的紙條筆記",
            "target_name": "6號車廂",
            "type": "located_in",
            "description": "紙條筆記貼在6號車廂的車廂門扉上。",
        },
        {
            "source_name": "紙條筆記",
            "target_name": "前進",
            "type": "objective_targets",
            "description": "紙條內容要求只管前進。",
        },
        {
            "source_name": "幸運判定",
            "target_name": "探索者們",
            "type": "applies_to",
            "description": "在6號車廂開始地點，全員需要進行幸運判定。",
        },
        {
            "source_name": "幸運判定",
            "target_name": "所持物品",
            "type": "resource",
            "description": "判定用來決定身上的所持物品的去留。",
        },
        {
            "source_name": "紙條筆記",
            "target_name": "第三個箱子裡有藏著鑰匙",
            "type": "reveals",
            "description": "紙條筆記背面寫有這條線索。",
        },
        {
            "source_name": "電車示意地圖",
            "target_name": "7號車廂以後被塗掉的部分",
            "type": "reveals",
            "description": "使用《靈感》判定成功後可得知地圖上7號車廂之後的部分被人蓄意塗掉。",
        },
        {
            "source_name": "7號車廂",
            "target_name": "血腥臭味",
            "type": "contains",
            "description": "前往7號車廂時會感覺到血腥臭味。",
        },
        {
            "source_name": "7號車廂",
            "target_name": "悲慘被撕裂的人體似的東西",
            "type": "contains",
            "description": "打開7號車廂的門後可看見散落一地的撕裂人體似的東西。",
        },
        {
            "source_name": "屍體",
            "target_name": "7號車廂",
            "type": "located_in",
            "description": "屍體位於7號車廂中。",
        },
        {
            "source_name": "第三個箱子裡有藏著鑰匙",
            "target_name": "3號車廂",
            "type": "points_to",
            "description": "這條線索實際指向3號車廂內藏有鑰匙。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "鑰匙",
            "type": "contains",
            "description": "線索表明鑰匙藏在3號車廂中。",
        },
        {
            "source_name": "電車示意地圖",
            "target_name": "蓄意塗掉的7號車廂以後區域",
            "type": "reveals",
            "description": "《靈感》成功後可得知地圖上7號車廂以後的區域被人蓄意塗掉。",
        },
        {
            "source_name": "7號車廂",
            "target_name": "被撕裂的人體似的東西",
            "type": "contains",
            "description": "打開7號車廂的門後會看到這個場景。",
        },
        {
            "source_name": "巨大類似嘴巴的東西",
            "target_name": "7號車輛",
            "type": "located_in",
            "description": "該巨大異常存在位於7號車輛深處。",
        },
        {
            "source_name": "巨大類似嘴巴的東西",
            "target_name": "車廂",
            "type": "attacks",
            "description": "它正在啃蝕車廂。",
        },
        {
            "source_name": "7號車輛",
            "target_name": "8號車廂",
            "type": "connected_to",
            "description": "文本描述中提到7號車輛往8號車廂的門。",
        },
        {
            "source_name": "7號車輛",
            "target_name": "8號車廂",
            "type": "blocked_by",
            "description": "失敗時，7號車輛往8號車廂的門不見了，只剩黑暗。",
        },
        {
            "source_name": "5號車廂",
            "target_name": "明天的報紙",
            "type": "contains",
            "description": "在5號車廂可找到報紙。",
        },
        {
            "source_name": "明天的報紙",
            "target_name": "昨晚OO線電車大規模的恐怖事件",
            "type": "reveals",
            "description": "報紙內容記載了昨晚OO線電車發生的大規模恐怖事件。",
        },
        {
            "source_name": "昨晚OO線電車大規模的恐怖事件",
            "target_name": "OO線電車",
            "type": "occurred_at",
            "description": "該恐怖事件發生在OO線電車上。",
        },
        {
            "source_name": "明天的報紙",
            "target_name": "精神病院",
            "type": "mentions",
            "description": "報紙提到倖存乘客被送往精神病院。",
        },
        {
            "source_name": "倖存乘客的精神異常",
            "target_name": "精神病院",
            "type": "resulted_in",
            "description": "倖存乘客精神變得異常後全部被送往精神病院。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "消失",
            "type": "threatened_by",
            "description": "靈感判定成功時可得知6號車廂已經快要有一半消失了。",
        },
        {
            "source_name": "巨大類似嘴巴的東西",
            "target_name": "7號車輛",
            "type": "located_in",
            "description": "該巨大異常存在位於7號車輛深處。",
        },
        {
            "source_name": "巨大類似嘴巴的東西",
            "target_name": "車廂",
            "type": "attacks",
            "description": "它正在啃蝕車廂。",
        },
        {
            "source_name": "7號車輛",
            "target_name": "8號車廂",
            "type": "connected_to",
            "description": "文本描述中提到7號車輛往8號車廂的門。",
        },
        {
            "source_name": "7號車輛",
            "target_name": "8號車廂",
            "type": "blocked_by",
            "description": "失敗時，7號車輛往8號車廂的門不見了，只剩黑暗。",
        },
        {
            "source_name": "5號車廂",
            "target_name": "報紙",
            "type": "contains",
            "description": "在5號車廂可找到報紙。",
        },
        {
            "source_name": "報紙",
            "target_name": "昨晚OO線電車大規模的恐怖事件",
            "type": "reveals",
            "description": "報紙內容記載了昨晚OO線電車發生的大規模恐怖事件。",
        },
        {
            "source_name": "昨晚OO線電車大規模的恐怖事件",
            "target_name": "OO線電車",
            "type": "occurred_at",
            "description": "該恐怖事件發生在OO線電車上。",
        },
        {
            "source_name": "報紙",
            "target_name": "來自明天的報紙",
            "type": "is_identified_as",
            "description": "經由圖書館或觀察判定後，報紙被識別為來自明天的報紙。",
        },
        {
            "source_name": "報紙",
            "target_name": "精神病院",
            "type": "mentions",
            "description": "報紙提到倖存乘客被送往精神病院。",
        },
        {
            "source_name": "倖存乘客的精神異常",
            "target_name": "精神病院",
            "type": "resulted_in",
            "description": "倖存乘客精神變得異常後全部被送往精神病院。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "消失",
            "type": "threatened_by",
            "description": "靈感判定成功時可得知6號車廂已經快要有一半消失了。",
        },
        {
            "source_name": "4號車廂",
            "target_name": "乘務員",
            "type": "located_in",
            "description": "瀕死的乘務員在4號車廂被發現。",
        },
        {
            "source_name": "乘務員",
            "target_name": "黑色包包",
            "type": "owns",
            "description": "乘務員原本隨身攜帶黑色包包。",
        },
        {
            "source_name": "乘務員",
            "target_name": "駕駛室房間鑰匙",
            "type": "knows_about",
            "description": "乘務員提到駕駛室房間鑰匙的存在與相關位置。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車控制面板鑰匙",
            "type": "knows_about",
            "description": "乘務員提到電車控制面板鑰匙曾放在自己的黑色包包中。",
        },
        {
            "source_name": "黑色包包",
            "target_name": "電車控制面板鑰匙",
            "type": "contained",
            "description": "電車控制面板鑰匙原本放在乘務員的黑色包包裡。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "電車控制面板鑰匙",
            "type": "located_in",
            "description": "乘務員表示電車控制面板鑰匙後來掉在3號車廂前門附近。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "3號車廂的前門附近",
            "type": "part_of",
            "description": "前門附近是3號車廂內的一處位置。",
        },
        {
            "source_name": "人型的什麼",
            "target_name": "乘務員",
            "type": "attacked",
            "description": "乘務員表示自己曾遭到某個人型存在襲擊。",
        },
        {
            "source_name": "人型的什麼",
            "target_name": "乘客",
            "type": "attacked",
            "description": "該人型存在開始襲擊乘客。",
        },
        {
            "source_name": "人型的什麼",
            "target_name": "乘客",
            "type": "eats",
            "description": "該人型存在以啃食方式傷害乘客。",
        },
        {
            "source_name": "5號車廂",
            "target_name": "Threat",
            "type": "related_to",
            "description": "超過行動限制時，5號車廂那一邊的門扉會發出異常聲響並伴隨立足點消失的現象。",
        },
        {
            "source_name": "4號車廂",
            "target_name": "乗務員",
            "type": "located_in",
            "description": "瀕死の乗務員は4號車廂で発見される。",
        },
        {
            "source_name": "乗務員",
            "target_name": "黑色包包",
            "type": "owns",
            "description": "乗務員は黒いバッグを所持していた。",
        },
        {
            "source_name": "黑色包包",
            "target_name": "電車控制面板鑰匙",
            "type": "contained",
            "description": "電車控制面板鑰匙は元々黒いバッグに入っていた。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "電車控制面板鑰匙",
            "type": "located_in",
            "description": "電車控制面板鑰匙は3號車廂の前門附近に落ちた可能性がある。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "3號車廂の前門附近",
            "type": "part_of",
            "description": "前門附近は3號車廂内の位置。",
        },
        {
            "source_name": "乗務員",
            "target_name": "人型的什麼",
            "type": "witnessed",
            "description": "乗務員は自分を襲った人型の何かを目撃したと語る。",
        },
        {
            "source_name": "人型的什麼",
            "target_name": "乘務員",
            "type": "attacked",
            "description": "人型の存在は乗務員を突然襲撃した。",
        },
        {
            "source_name": "人型的什麼",
            "target_name": "乘客",
            "type": "attacked",
            "description": "人型の存在は乗客を次々に襲った。",
        },
        {
            "source_name": "人型的什麼",
            "target_name": "乘客",
            "type": "eats",
            "description": "人型の存在は乗客を獣のように噛み食っていた。",
        },
        {
            "source_name": "襲擊者",
            "target_name": "乘客",
            "type": "attacks",
            "description": "襲擊者逐一襲擊並咬食乘客。",
        },
        {
            "source_name": "襲擊者",
            "target_name": "乘務員",
            "type": "attacks",
            "description": "乘務員表示自己曾被襲擊者咬傷腿部。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車",
            "type": "located_in",
            "description": "乘務員在電車上遭到襲擊。",
        },
        {
            "source_name": "乘務員",
            "target_name": "探索者隊伍",
            "type": "joins",
            "description": "乘務員請求幫助後加入探索者隊伍。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車",
            "type": "requests_stop",
            "description": "乘務員請求將電車停下來以便逃跑。",
        },
        {
            "source_name": "咬痕",
            "target_name": "乘務員",
            "type": "evidence_about",
            "description": "乘務員腿上的咬痕支持他遭到襲擊的說法。",
        },
        {
            "source_name": "聲響",
            "target_name": "襲擊者",
            "type": "attracts",
            "description": "襲擊者對聲音似乎很敏感，大聲響會吸引其注意。",
        },
        {
            "source_name": "行李",
            "target_name": "聲響",
            "type": "used_to_create",
            "description": "把行李扔向牆壁可以製造大聲響。",
        },
        {
            "source_name": "行李",
            "target_name": "牆壁",
            "type": "thrown_against",
            "description": "乘務員提到將行李扔向牆壁。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "auto_succeeds_finding",
            "description": "若由乘務員同行，尋找鑰匙會變成自動成功。",
        },
        {
            "source_name": "乘務員",
            "target_name": "3號車廂",
            "type": "should_not_be_left_in",
            "description": "若在前往3號車廂時把乘務員放置在那裡，他會被黑暗吞噬。",
        },
        {
            "source_name": "黑暗吞噬",
            "target_name": "乘務員",
            "type": "threatens",
            "description": "黑暗吞噬會吞噬被留在3號車廂的乘務員。",
        },
        {
            "source_name": "襲擊者",
            "target_name": "乘客",
            "type": "attacks",
            "description": "襲擊者逐一襲擊並咬食乘客。",
        },
        {
            "source_name": "襲擊者",
            "target_name": "乘務員",
            "type": "attacks",
            "description": "乘務員表示自己曾被襲擊者咬傷腿部。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車",
            "type": "located_in",
            "description": "乘務員在電車上遭到襲擊。",
        },
        {
            "source_name": "乘務員",
            "target_name": "探索者隊伍",
            "type": "joins",
            "description": "乘務員請求幫助後加入探索者隊伍。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車",
            "type": "requests_stop",
            "description": "乘務員請求將電車停下來以便逃跑。",
        },
        {
            "source_name": "咬痕",
            "target_name": "乘務員",
            "type": "evidence_about",
            "description": "乘務員腿上的咬痕支持他遭到襲擊的說法。",
        },
        {
            "source_name": "聲響",
            "target_name": "襲擊者",
            "type": "attracts",
            "description": "襲擊者對聲音似乎很敏感，大聲響會吸引其注意。",
        },
        {
            "source_name": "行李",
            "target_name": "聲響",
            "type": "used_to_create",
            "description": "把行李扔向牆壁可以製造大聲響。",
        },
        {
            "source_name": "行李",
            "target_name": "牆壁",
            "type": "thrown_against",
            "description": "乘務員提到將行李扔向牆壁。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "auto_succeeds_finding",
            "description": "若由乘務員同行，尋找鑰匙會變成自動成功。",
        },
        {
            "source_name": "乘務員",
            "target_name": "3號車廂",
            "type": "should_not_be_left_in",
            "description": "若在前往3號車廂時把乘務員放置在那裡，他會被黑暗吞噬。",
        },
        {
            "source_name": "黑暗吞噬",
            "target_name": "乘務員",
            "type": "threatens",
            "description": "黑暗吞噬會吞噬被留在3號車廂的乘務員。",
        },
        {
            "source_name": "乘務員",
            "target_name": "3號車廂",
            "type": "located_in",
            "description": "乘務員若被放置在前往3号车厢时，会在那里被黑暗吞噬。",
        },
        {
            "source_name": "黑暗",
            "target_name": "乘務員",
            "type": "threatens",
            "description": "黑暗会吞噬被放置到3号车厢那边的乘务员。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "怪物",
            "type": "does_not_contain",
            "description": "对通往3号车厢的门扉使用观察可得知，3号车厢里没有怪物。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "鑰匙",
            "type": "contains",
            "description": "钥匙可在3号车厢中被寻找并找到。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "knows_about",
            "description": "如果已经询问过钥匙所在，搜索钥匙时观察会获得补正；说明乘务员可提供钥匙位置相关信息。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "holds",
            "description": "找到钥匙时，乘务员会表示要负起责任并让自己拿着钥匙。",
        },
        {
            "source_name": "探索者",
            "target_name": "鑰匙",
            "type": "can_obtain",
            "description": "可以通过说服或快速交谈让探索者拿到钥匙。",
        },
        {
            "source_name": "乘務員",
            "target_name": "隨身物品",
            "type": "enables_recovery_of",
            "description": "根据GM意思，乘务员在场时，玩家也可能在3号车厢找回之前弄丢的随身物品。",
        },
        {
            "source_name": "隨身物品",
            "target_name": "隨身攜帶包",
            "type": "includes",
            "description": "成功时可找回自己的随身携带包。",
        },
        {
            "source_name": "打火機",
            "target_name": "2號車廂",
            "type": "illuminates",
            "description": "用打火机查看2号车厢内部。",
        },
        {
            "source_name": "手電筒",
            "target_name": "2號車廂",
            "type": "illuminates",
            "description": "用手电筒查看2号车厢内部。",
        },
        {
            "source_name": "觀察",
            "target_name": "3號車廂",
            "type": "reveals",
            "description": "对通往3号车厢的门扉使用观察可知道车厢内没有怪物。",
        },
        {
            "source_name": "說服",
            "target_name": "乘務員",
            "type": "can_influence",
            "description": "可用说服让乘务员把钥匙交给探索者。",
        },
        {
            "source_name": "快速交談",
            "target_name": "乘務員",
            "type": "can_influence",
            "description": "可用快速交谈让乘务员把钥匙交给探索者。",
        },
        {
            "source_name": "知識",
            "target_name": "鑰匙",
            "type": "reveals",
            "description": "如果没有问过乘务员是哪边的钥匙，可以用知识判定来了解钥匙相关信息。",
        },
        {
            "source_name": "幸運",
            "target_name": "隨身物品",
            "type": "can_recover",
            "description": "成功的幸运判定可找回自己的随身携带包等遗失随身物品。",
        },
        {
            "source_name": "乘務員",
            "target_name": "3號車廂",
            "type": "located_in",
            "description": "乘务员若被放置在前往3号车厢时，会在那里被黑暗吞噬。",
        },
        {
            "source_name": "黑暗",
            "target_name": "乘務員",
            "type": "threatens",
            "description": "黑暗会吞噬被放置到3号车厢那边的乘务员。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "怪物",
            "type": "does_not_contain",
            "description": "对通往3号车厢的门扉使用观察可得知，3号车厢里没有怪物。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "鑰匙",
            "type": "contains",
            "description": "钥匙可在3号车厢中被寻找并找到。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "knows_about",
            "description": "如果已经询问过钥匙所在，搜索钥匙时观察会获得补正；说明乘务员可提供钥匙位置相关信息。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "holds",
            "description": "找到钥匙时，乘务员会表示要负起责任并让自己拿着钥匙。",
        },
        {
            "source_name": "探索者",
            "target_name": "鑰匙",
            "type": "can_obtain",
            "description": "可以通过说服或快速交谈让探索者拿到钥匙。",
        },
        {
            "source_name": "乘務員",
            "target_name": "隨身物品",
            "type": "enables_recovery_of",
            "description": "根据GM意思，乘务员在场时，玩家也可能在3号车厢找回之前弄丢的随身物品。",
        },
        {
            "source_name": "隨身物品",
            "target_name": "隨身攜帶包",
            "type": "includes",
            "description": "成功时可找回自己的随身携带包。",
        },
        {
            "source_name": "打火機",
            "target_name": "2號車廂",
            "type": "illuminates",
            "description": "用打火机查看2号车厢内部。",
        },
        {
            "source_name": "手電筒",
            "target_name": "2號車廂",
            "type": "illuminates",
            "description": "用手电筒查看2号车厢内部。",
        },
        {
            "source_name": "觀察",
            "target_name": "3號車廂",
            "type": "reveals",
            "description": "对通往3号车厢的门扉使用观察可知道车厢内没有怪物。",
        },
        {
            "source_name": "說服",
            "target_name": "乘務員",
            "type": "can_influence",
            "description": "可用说服让乘务员把钥匙交给探索者。",
        },
        {
            "source_name": "快速交談",
            "target_name": "乘務員",
            "type": "can_influence",
            "description": "可用快速交谈让乘务员把钥匙交给探索者。",
        },
        {
            "source_name": "知識",
            "target_name": "鑰匙",
            "type": "reveals",
            "description": "如果没有问过乘务员是哪边的钥匙，可以用知识判定来了解钥匙相关信息。",
        },
        {
            "source_name": "幸運",
            "target_name": "隨身物品",
            "type": "can_recover",
            "description": "成功的幸运判定可找回自己的随身携带包等遗失随身物品。",
        },
        {
            "source_name": "2號車廂",
            "target_name": "clicker",
            "type": "contains",
            "description": "2號車廂中有 clicker 出沒。",
        },
        {
            "source_name": "手電筒",
            "target_name": "2號車廂",
            "type": "helps_explore",
            "description": "在2號車廂使用手電筒可讓《觀察》獲得加成。",
        },
        {
            "source_name": "智慧型手機",
            "target_name": "2號車廂",
            "type": "helps_explore",
            "description": "在2號車廂使用較小光源的智慧型手機可讓《觀察》獲得少量加成。",
        },
        {
            "source_name": "打火機",
            "target_name": "2號車廂",
            "type": "illuminates",
            "description": "打火機可用來照亮2號車廂。",
        },
        {
            "source_name": "clicker",
            "target_name": "視力",
            "type": "lacks",
            "description": "clicker 沒有視力。",
        },
        {
            "source_name": "clicker",
            "target_name": "眼睛",
            "type": "lacks",
            "description": "探索者可注意到 clicker 的上半部頭顱沒有眼睛。",
        },
        {
            "source_name": "clicker",
            "target_name": "SAN減少",
            "type": "causes",
            "description": "看到 clicker 的 PL 會造成 SAN1/1d8 的減少。",
        },
        {
            "source_name": "被撕裂破碎的屍體和鮮血惡臭",
            "target_name": "SAN減少",
            "type": "causes",
            "description": "若探索者未在7號車廂見過該景象，相關遭遇會導致 SAN0/1 的減少。",
        },
        {
            "source_name": "乘務員",
            "target_name": "襲擊乘務員的怪物",
            "type": "victim_of",
            "description": "乘務員曾遭該怪物襲擊。",
        },
        {
            "source_name": "clicker",
            "target_name": "2號車廂",
            "type": "located_in",
            "description": "clicker 出现在2號車廂。",
        },
        {
            "source_name": "2號車廂",
            "target_name": "clicker",
            "type": "contains",
            "description": "2號車廂内有 clicker。",
        },
        {
            "source_name": "clicker",
            "target_name": "視力",
            "type": "lacks",
            "description": "clicker 沒有視力。",
        },
        {
            "source_name": "clicker",
            "target_name": "眼睛",
            "type": "lacks",
            "description": "clicker 的上半部頭顱没有眼睛。",
        },
        {
            "source_name": "手電筒",
            "target_name": "2號車廂",
            "type": "helps_explore",
            "description": "在2號車廂使用手電筒可让《觀察》获得加成。",
        },
        {
            "source_name": "智慧型手機",
            "target_name": "2號車廂",
            "type": "helps_explore",
            "description": "在2號車廂使用智慧型手機類较小光源可让《觀察》获得少量加成。",
        },
        {
            "source_name": "打火機",
            "target_name": "2號車廂",
            "type": "illuminates",
            "description": "打火機可用于照亮2號車廂。",
        },
        {
            "source_name": "被撕裂破碎的屍體與鮮血惡臭",
            "target_name": "SAN減少",
            "type": "causes",
            "description": "若探索者未在7號車廂先见过该景象，后续遭遇会造成 SAN 0/1 的减少。",
        },
        {
            "source_name": "襲擊了乘務員的怪物",
            "target_name": "乘務員",
            "type": "attacked",
            "description": "该怪物曾袭击乘务员。",
        },
        {
            "source_name": "clicker",
            "target_name": "車廂",
            "type": "located_in",
            "description": "clicker出現在車廂中。",
        },
        {
            "source_name": "探索者",
            "target_name": "車廂",
            "type": "located_in",
            "description": "探索者在車廂內行動、潛行通過。",
        },
        {
            "source_name": "屍體",
            "target_name": "車廂",
            "type": "located_in",
            "description": "屍體位於車廂地面附近，行動時可能踩到。",
        },
        {
            "source_name": "聲響",
            "target_name": "clicker",
            "type": "clue_points_to",
            "description": "製造聲響會吸引clicker注意。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "can_obtain",
            "description": "若有探索者幸運判定成功，可能在乘務員被抓走前取得鑰匙。",
        },
        {
            "source_name": "乘務員",
            "target_name": "clicker",
            "type": "threatened_by",
            "description": "乘務員失敗後會被抓住。",
        },
        {
            "source_name": "探索者",
            "target_name": "戰鬥",
            "type": "may_enter",
            "description": "若後續失敗且無法逃脫，可能進入戰鬥。",
        },
        {
            "source_name": "clicker",
            "target_name": "戰鬥",
            "type": "threatens",
            "description": "clicker的出現可能導致進入戰鬥。",
        },
        {
            "source_name": "clicker",
            "target_name": "車廂",
            "type": "located_in",
            "description": "clicker出現在車廂中。",
        },
        {
            "source_name": "探索者",
            "target_name": "車廂",
            "type": "located_in",
            "description": "探索者在車廂內行動、潛行通過。",
        },
        {
            "source_name": "屍體",
            "target_name": "車廂",
            "type": "located_in",
            "description": "屍體位於車廂地面附近，行動時可能踩到。",
        },
        {
            "source_name": "聲響",
            "target_name": "clicker",
            "type": "clue_points_to",
            "description": "製造聲響會吸引clicker注意。",
        },
        {
            "source_name": "乘務員",
            "target_name": "鑰匙",
            "type": "can_obtain",
            "description": "若有探索者幸運判定成功，可能在乘務員被抓走前取得鑰匙。",
        },
        {
            "source_name": "乘務員",
            "target_name": "clicker",
            "type": "threatened_by",
            "description": "乘務員失敗後會被抓住。",
        },
        {
            "source_name": "探索者",
            "target_name": "戰鬥",
            "type": "may_enter",
            "description": "若後續失敗且無法逃脫，可能進入戰鬥。",
        },
        {
            "source_name": "clicker",
            "target_name": "戰鬥",
            "type": "threatens",
            "description": "clicker的出現可能導致進入戰鬥。",
        },
        {
            "source_name": "先頭車廂",
            "target_name": "二號車廂",
            "type": "different_from",
            "description": "先頭車廂被描述為和二號車廂完全不同。",
        },
        {
            "source_name": "駕駛室",
            "target_name": "鑰匙",
            "type": "requires",
            "description": "進入駕駛室需要使用鑰匙開門。",
        },
        {
            "source_name": "操作面板",
            "target_name": "鑰匙",
            "type": "requires",
            "description": "操作面板可用鑰匙打開。",
        },
        {
            "source_name": "駕駛室",
            "target_name": "操作面板",
            "type": "contains",
            "description": "駕駛室內有操作面板。",
        },
        {
            "source_name": "控制拉桿",
            "target_name": "左邊的拉桿",
            "type": "includes",
            "description": "控制拉桿包含左邊的拉桿。",
        },
        {
            "source_name": "控制拉桿",
            "target_name": "右邊的拉桿",
            "type": "includes",
            "description": "控制拉桿包含右邊的拉桿。",
        },
        {
            "source_name": "左邊的拉桿",
            "target_name": "電車",
            "type": "controls",
            "description": "左邊的拉桿用於控制電車的煞車與起步。",
        },
        {
            "source_name": "右邊的拉桿",
            "target_name": "電車",
            "type": "controls",
            "description": "右邊的拉桿用於控制電車的油門、加速與減速。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車",
            "type": "wants_to_stop",
            "description": "若乘務員在場，他會不由分說想把電車停下來。",
        },
        {
            "source_name": "說服",
            "target_name": "乘務員",
            "type": "can_block_or_change",
            "description": "可用說服來阻止或改變乘務員想停下電車的行動。",
        },
        {
            "source_name": "快速交談",
            "target_name": "乘務員",
            "type": "can_block_or_change",
            "description": "可用快速交談來阻止或改變乘務員想停下電車的行動。",
        },
        {
            "source_name": "STR對抗",
            "target_name": "乘務員",
            "type": "can_block_or_change",
            "description": "可用STR對抗來阻止或改變乘務員想停下電車的行動。",
        },
        {
            "source_name": "探索者",
            "target_name": "戰鬥",
            "type": "is_disadvantaged_in",
            "description": "文本指出此處戰鬥對探索者極為不利，基本上絕對打不贏。",
        },
        {
            "source_name": "先頭車廂",
            "target_name": "戰鬥",
            "type": "is_disadvantaged_in",
            "description": "先頭車廂附近黑暗且散落物品眾多，使戰鬥狀況十分惡劣。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車駕駛基本知識",
            "type": "provides",
            "description": "詢問乘務員可得到電車駕駛基本知識。",
        },
        {
            "source_name": "電車駕駛基本知識",
            "target_name": "左邊的拉桿",
            "type": "explains",
            "description": "知識內容說明左桿是煞車起步裝置。",
        },
        {
            "source_name": "電車駕駛基本知識",
            "target_name": "右邊的拉桿",
            "type": "explains",
            "description": "知識內容說明右桿是油門。",
        },
        {
            "source_name": "電車駕駛基本知識",
            "target_name": "右邊的拉桿",
            "type": "explains",
            "description": "知識內容說明右桿往下拉可加速、往上拉可減速。",
        },
        {
            "source_name": "先頭車廂",
            "target_name": "二號車廂",
            "type": "different_from",
            "description": "先頭車廂被描述為和二號車廂完全不同。",
        },
        {
            "source_name": "駕駛室",
            "target_name": "鑰匙",
            "type": "requires",
            "description": "進入駕駛室需要使用鑰匙開門。",
        },
        {
            "source_name": "操作面板",
            "target_name": "鑰匙",
            "type": "requires",
            "description": "操作面板可用鑰匙打開。",
        },
        {
            "source_name": "駕駛室",
            "target_name": "操作面板",
            "type": "contains",
            "description": "駕駛室內有操作面板。",
        },
        {
            "source_name": "控制拉桿",
            "target_name": "左邊的拉桿",
            "type": "includes",
            "description": "控制拉桿包含左邊的拉桿。",
        },
        {
            "source_name": "控制拉桿",
            "target_name": "右邊的拉桿",
            "type": "includes",
            "description": "控制拉桿包含右邊的拉桿。",
        },
        {
            "source_name": "左邊的拉桿",
            "target_name": "電車",
            "type": "controls",
            "description": "左邊的拉桿用於控制電車的煞車與起步。",
        },
        {
            "source_name": "右邊的拉桿",
            "target_name": "電車",
            "type": "controls",
            "description": "右邊的拉桿用於控制電車的油門、加速與減速。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車",
            "type": "wants_to_stop",
            "description": "若乘務員在場，他會不由分說想把電車停下來。",
        },
        {
            "source_name": "說服",
            "target_name": "乘務員",
            "type": "can_block_or_change",
            "description": "可用說服來阻止或改變乘務員想停下電車的行動。",
        },
        {
            "source_name": "快速交談",
            "target_name": "乘務員",
            "type": "can_block_or_change",
            "description": "可用快速交談來阻止或改變乘務員想停下電車的行動。",
        },
        {
            "source_name": "STR對抗",
            "target_name": "乘務員",
            "type": "can_block_or_change",
            "description": "可用STR對抗來阻止或改變乘務員想停下電車的行動。",
        },
        {
            "source_name": "探索者",
            "target_name": "戰鬥",
            "type": "is_disadvantaged_in",
            "description": "文本指出此處戰鬥對探索者極為不利，基本上絕對打不贏。",
        },
        {
            "source_name": "先頭車廂",
            "target_name": "戰鬥",
            "type": "is_disadvantaged_in",
            "description": "先頭車廂附近黑暗且散落物品眾多，使戰鬥狀況十分惡劣。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車駕駛基本知識",
            "type": "provides",
            "description": "詢問乘務員可得到電車駕駛基本知識。",
        },
        {
            "source_name": "電車駕駛基本知識",
            "target_name": "左邊的拉桿",
            "type": "explains",
            "description": "知識內容說明左桿是煞車起步裝置。",
        },
        {
            "source_name": "電車駕駛基本知識",
            "target_name": "右邊的拉桿",
            "type": "explains",
            "description": "知識內容說明右桿是油門。",
        },
        {
            "source_name": "電車駕駛基本知識",
            "target_name": "右邊的拉桿",
            "type": "explains",
            "description": "知識內容說明右桿往下拉可加速、往上拉可減速。",
        },
        {
            "source_name": "探索者",
            "target_name": "電車",
            "type": "located_in",
            "description": "探索者乘坐並身處電車之中。",
        },
        {
            "source_name": "加速",
            "target_name": "結局A",
            "type": "causes",
            "description": "文本指示若採用加速，進入結局A。",
        },
        {
            "source_name": "減速",
            "target_name": "結局B",
            "type": "causes",
            "description": "文本指示若採用減速，進入結局B。",
        },
        {
            "source_name": "結局A",
            "target_name": "True End",
            "type": "alias_of",
            "description": "結局A被標示為True End。",
        },
        {
            "source_name": "結局B",
            "target_name": "BAD END",
            "type": "alias_of",
            "description": "結局B被標示為BAD END。",
        },
        {
            "source_name": "結局A",
            "target_name": "6號車廂",
            "type": "occurred_at",
            "description": "結局A中探索者醒來時回到睡著前的6號車廂。",
        },
        {
            "source_name": "結局A",
            "target_name": "停靠站",
            "type": "occurred_at",
            "description": "結局A中電車抵達熟悉的停靠站。",
        },
        {
            "source_name": "站務人員",
            "target_name": "探索者",
            "type": "addresses",
            "description": "結局A中站務人員詢問探索者是否沒事。",
        },
        {
            "source_name": "站務人員",
            "target_name": "乘務員NPC",
            "type": "does_not_recognize",
            "description": "若探索者詢問乘務員NPC，站務員表示不認識或沒有這樣的人。",
        },
        {
            "source_name": "乘務員NPC",
            "target_name": "電車",
            "type": "associated_with",
            "description": "乘務員NPC被作為電車上的相關角色被提及，但其存在在結局A中受到否認。",
        },
        {
            "source_name": "結局B",
            "target_name": "屍塊",
            "type": "contains",
            "description": "BAD END中描寫列車停下時周遭遍布殘缺腐爛的屍塊。",
        },
        {
            "source_name": "結局B",
            "target_name": "血水",
            "type": "contains",
            "description": "BAD END中描寫列車停下時周遭遍布血水。",
        },
        {
            "source_name": "結局B",
            "target_name": "鐵鏽的味道",
            "type": "contains",
            "description": "BAD END中描寫場景充滿鐵鏽味。",
        },
        {
            "source_name": "結局B",
            "target_name": "咀嚼聲",
            "type": "contains",
            "description": "BAD END中有趴哩啪哩與嘓哩嘓哩的咀嚼聲逐漸接近。",
        },
        {
            "source_name": "加速",
            "target_name": "結局A",
            "type": "causes",
            "description": "原文明確表示如果加速，則進入結局A。",
        },
        {
            "source_name": "減速",
            "target_name": "結局B",
            "type": "causes",
            "description": "原文明確表示如果減速，則進入結局B。",
        },
        {
            "source_name": "結局A",
            "target_name": "現實世界",
            "type": "returns_to",
            "description": "結局A中探索者回到睡著前的狀態，並被明確確認是在現實世界。",
        },
        {
            "source_name": "結局B",
            "target_name": "殘缺腐爛的屍塊",
            "type": "contains",
            "description": "結局B中列車停下後，腳下遍布殘缺腐爛的屍塊。",
        },
        {
            "source_name": "結局B",
            "target_name": "血水",
            "type": "contains",
            "description": "結局B中列車停下後，腳下遍布血水。",
        },
        {
            "source_name": "結局B",
            "target_name": "鐵鏽的味道",
            "type": "contains",
            "description": "結局B中有強烈的鐵鏽味直衝腦門。",
        },
        {
            "source_name": "結局B",
            "target_name": "趴哩啪哩的咀嚼聲",
            "type": "contains",
            "description": "結局B中出現並逐漸接近的咀嚼聲。",
        },
        {
            "source_name": "趴哩啪哩的咀嚼聲",
            "target_name": "嘓哩嘓哩的咀嚼音",
            "type": "alias_of",
            "description": "兩者都是對結局B中咀嚼聲的不同擬聲描述。",
        },
        {
            "source_name": "黑色包",
            "target_name": "探索者",
            "type": "located_in",
            "description": "黑色包出現在一位探索者的所持物品中。",
        },
        {
            "source_name": "黏在門上的筆記",
            "target_name": "6號車廂",
            "type": "located_in",
            "description": "筆記黏在6號車廂的門上。",
        },
        {
            "source_name": "黏在門上的筆記",
            "target_name": "3號車廂",
            "type": "clue_reveals",
            "description": "筆記背面寫到3號車廂的事情。",
        },
        {
            "source_name": "報紙",
            "target_name": "5號車廂",
            "type": "located_in",
            "description": "理想流程中在5號車廂看到報紙。",
        },
        {
            "source_name": "結局A",
            "target_name": "生還",
            "type": "objective_targets",
            "description": "達成結局A時可領取與生還相關的SAN值回復報酬。",
        },
        {
            "source_name": "結局A",
            "target_name": "乘務員",
            "type": "objective_targets",
            "description": "達成結局A時，乘務員生還數會影響SAN值回復報酬。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "3號車廂",
            "type": "connected_to",
            "description": "理想流程中由6號車廂筆記引出對3號車廂的資訊。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "報紙",
            "type": "connected_to",
            "description": "理想流程顯示接著前往5號車廂看報紙以掌握狀況。",
        },
        {
            "source_name": "黑色包",
            "target_name": "探索者",
            "type": "located_in",
            "description": "黑色包出現在一位探索者的所持物品中。",
        },
        {
            "source_name": "黏在門上的筆記",
            "target_name": "6號車廂",
            "type": "located_in",
            "description": "筆記黏在6號車廂的門上。",
        },
        {
            "source_name": "黏在門上的筆記",
            "target_name": "3號車廂",
            "type": "clue_reveals",
            "description": "筆記背面寫到3號車廂的事情。",
        },
        {
            "source_name": "報紙",
            "target_name": "5號車廂",
            "type": "located_in",
            "description": "理想流程中在5號車廂看到報紙。",
        },
        {
            "source_name": "結局A",
            "target_name": "生還",
            "type": "objective_targets",
            "description": "達成結局A時可領取與生還相關的SAN值回復報酬。",
        },
        {
            "source_name": "結局A",
            "target_name": "乘務員",
            "type": "objective_targets",
            "description": "達成結局A時，乘務員生還數會影響SAN值回復報酬。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "3號車廂",
            "type": "connected_to",
            "description": "理想流程中由6號車廂筆記引出對3號車廂的資訊。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "報紙",
            "type": "connected_to",
            "description": "理想流程顯示接著前往5號車廂看報紙以掌握狀況。",
        },
        {
            "source_name": "5號車廂",
            "target_name": "報紙",
            "type": "contains",
            "description": "在5號車廂看到報紙。",
        },
        {
            "source_name": "報紙",
            "target_name": "現在的狀況",
            "type": "reveals",
            "description": "透過報紙掌握了現在的狀況。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "消失",
            "type": "associated_with",
            "description": "注意到6號車廂的消失。",
        },
        {
            "source_name": "探索者們",
            "target_name": "之前的車廂",
            "type": "cannot_return_to",
            "description": "注意到無法返回之前的車廂。",
        },
        {
            "source_name": "4號車廂",
            "target_name": "乘務員",
            "type": "helps",
            "description": "在4號車廂幫助了乘務員。",
        },
        {
            "source_name": "4號車廂",
            "target_name": "鑰匙",
            "type": "reveals_location_of",
            "description": "在4號車廂得知鑰匙的所在地。",
        },
        {
            "source_name": "4號車廂",
            "target_name": "乘務員",
            "type": "travels_with",
            "description": "在4號車廂可選擇與乘務員一起同行。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "鑰匙",
            "type": "contains",
            "description": "在3號車廂找到鑰匙。",
        },
        {
            "source_name": "探索者們",
            "target_name": "鑰匙",
            "type": "takes",
            "description": "探索者們拿走了鑰匙。",
        },
        {
            "source_name": "2號車廂",
            "target_name": "通過",
            "type": "allows_silent_passage",
            "description": "可不出聲音地溜過2號車廂。",
        },
        {
            "source_name": "探索者們",
            "target_name": "先頭車廂",
            "type": "reaches",
            "description": "流程指向前往先頭車廂。",
        },
        {
            "source_name": "探索者們",
            "target_name": "鑰匙",
            "type": "uses",
            "description": "使用找到的鑰匙。",
        },
        {
            "source_name": "鑰匙",
            "target_name": "控制面板",
            "type": "activates",
            "description": "用鑰匙啟動控制面板。",
        },
        {
            "source_name": "控制面板",
            "target_name": "電車",
            "type": "increases_speed_of",
            "description": "啟動控制面板後使電車達到最高速。",
        },
        {
            "source_name": "筆記",
            "target_name": "電車",
            "type": "instructs_to_speed_up",
            "description": "筆記提示要將電車加速。",
        },
        {
            "source_name": "乘務員",
            "target_name": "京山 人吉",
            "type": "identity",
            "description": "乘務員的姓名是京山 人吉。",
        },
        {
            "source_name": "乘務員",
            "target_name": "電車",
            "type": "works_on",
            "description": "乘務員是電車上的工作人員。",
        },
        {
            "source_name": "京山 人吉",
            "target_name": "Clicker",
            "type": "wants_to_escape_from",
            "description": "他想要從Clicker手中脫逃。",
        },
        {
            "source_name": "京山 人吉",
            "target_name": "電車",
            "type": "wants_to_stop",
            "description": "他想要停下電車。",
        },
        {
            "source_name": "京山 人吉",
            "target_name": "5-7號車廂",
            "type": "lacks_information_about",
            "description": "他並不知道5-7號車廂的情報。",
        },
        {
            "source_name": "Clicker",
            "target_name": "敵方NPC",
            "type": "is",
            "description": "Clicker是敵方NPC。",
        },
        {
            "source_name": "Clicker",
            "target_name": "探索者們",
            "type": "threatens",
            "description": "Clicker是探索者們需要面對的敵方威脅。",
        },
        {
            "source_name": "Clicker",
            "target_name": "光源",
            "type": "unaffected_by",
            "description": "Clicker對光源沒有任何反應。",
        },
        {
            "source_name": "Clicker",
            "target_name": "眼睛",
            "type": "lacks",
            "description": "Clicker沒有眼睛。",
        },
        {
            "source_name": "逃出",
            "target_name": "電車",
            "type": "objective_involves",
            "description": "逃出的目標與電車情境相關。",
        },
        {
            "source_name": "逃出",
            "target_name": "Clicker",
            "type": "objective_avoids",
            "description": "逃出旨在脫離循聲者/Clicker的威脅。",
        },
        {
            "source_name": "3號車廂",
            "target_name": "背面",
            "type": "has_inscription_on",
            "description": "原文提到背面有寫到3號車廂的事情。",
        },
        {
            "source_name": "背面",
            "target_name": "3號車廂",
            "type": "mentions",
            "description": "背面寫有3號車廂的事情。",
        },
        {
            "source_name": "6號車廂",
            "target_name": "消失",
            "type": "caused_by_or_resulted_in",
            "description": "原文明確指出注意到6號車廂的消失。",
        },
        {
            "source_name": "探索者們",
            "target_name": "無法返回之前的車廂",
            "type": "notice",
            "description": "探索者們注意到無法返回之前的車廂的事實。",
        },
        {
            "source_name": "報紙",
            "target_name": "現在的狀況",
            "type": "reveals",
            "description": "在5號車廂看到報紙後掌握了現在的狀況。",
        },
        {
            "source_name": "京山 人吉",
            "target_name": "5-7號車廂",
            "type": "lacks_information_about",
            "description": "京山 人吉不知道5-7號車廂的情報。",
        },
        {
            "source_name": "京山 人吉",
            "target_name": "電車",
            "type": "wants_to_stop",
            "description": "京山 人吉想停下電車。",
        },
        {
            "source_name": "京山 人吉",
            "target_name": "Clicker",
            "type": "wants_to_escape_from",
            "description": "京山 人吉想從Clicker手中脫逃。",
        },
        {
            "source_name": "Clicker",
            "target_name": "光源",
            "type": "unaffected_by",
            "description": "Clicker對光源沒有任何反應。",
        },
        {
            "source_name": "Clicker",
            "target_name": "眼睛",
            "type": "lacks",
            "description": "Clicker沒有眼睛。",
        },
        {
            "source_name": "阿巴頓",
            "target_name": "深淵之王",
            "type": "identity",
            "description": "阿巴頓被稱為深淵之王。",
        },
        {
            "source_name": "追逐電車的大嘴",
            "target_name": "阿巴頓",
            "type": "identity",
            "description": "追逐電車的大嘴的正體為阿巴頓。",
        },
        {
            "source_name": "敵方NPC",
            "target_name": "光源",
            "type": "affected_by",
            "description": "敵方NPC對光源沒有任何反應，光源可作為對付它們的手段。",
        },
        {
            "source_name": "敵方NPC",
            "target_name": "聲響",
            "type": "sensitive_to",
            "description": "敵方NPC對聲音極度敏感。",
        },
        {
            "source_name": "投擲技能",
            "target_name": "聲響",
            "type": "used_to_create",
            "description": "可透過丟東西製造聲響來運用投擲技能。",
        },
        {
            "source_name": "返回的電車門",
            "target_name": "電車",
            "type": "part_of",
            "description": "返回的電車門屬於電車的一部分。",
        },
        {
            "source_name": "電車被啃食",
            "target_name": "電車",
            "type": "occurs_at",
            "description": "電車被啃食是發生在電車上的狀況。",
        },
        {
            "source_name": "電車被啃食",
            "target_name": "追逐電車的大嘴",
            "type": "caused_by",
            "description": "電車被啃食與追逐電車的大嘴有關。",
        },
        {
            "source_name": "敵方NPC",
            "target_name": "聲音",
            "type": "sensitive_to",
            "description": "敵方NPC對聲音極度敏感。",
        },
        {
            "source_name": "敵方NPC",
            "target_name": "光源",
            "type": "unaffected_by",
            "description": "敵方NPC對光源沒有任何反應。",
        },
    ],
}

# deduplicate entities
entities = data["entities"]
deduplicated_entities = {}
for entity in entities:
    if entity["name"] in deduplicated_entities:
        deduplicated_entities[entity["name"]]["description"].append(
            entity["description"]
        )
    else:
        deduplicated_entities[entity["name"]] = {
            "name": entity["name"],
            "type": entity["type"],
            "description": [entity["description"]],
        }

entities = list(deduplicated_entities.values())


async def main():
    async with neo4j_driver.session() as session:
        # create entities
        for entity in entities:
            await session.run(
                "CREATE (n:Entity {name: $name, type: $type, description: $description})",
                name=entity["name"],
                type=entity["type"],
                description=entity["description"],
            )

        # create relationships
        for relationship in data["relationships"]:
            await session.run(
                """
                    MATCH (a:Entity {name: $name1}), (b:Entity {name: $name2})
                    CREATE (a)-[:RELATION {type: $type, description: $description}]->(b)
                """,
                name1=relationship["source_name"],
                name2=relationship["target_name"],
                type=relationship["type"],
                description=relationship["description"],
            )


if __name__ == "__main__":
    asyncio.run(main())
