# type: ignore[reportAttributeAccessIssue]

"""add_debug_detail_to_room_messages

Revision ID: c831eb0ed613
Revises: d6a1a0bcdc6a
Create Date: 2026-06-08 17:29:12.859242

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'c831eb0ed613'
down_revision: Union[str, None] = 'd6a1a0bcdc6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_messages', sa.Column('detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_messages', 'detail')
    # ### end Alembic commands ###
