# type: ignore[reportAttributeAccessIssue]

"""add room_message llm_calls

Revision ID: 773a85736d67
Revises: 48102564a2c4
Create Date: 2026-06-10 00:51:27.223814

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '773a85736d67'
down_revision: Union[str, None] = '48102564a2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_processing_llm_calls_run_id_fkey'), 'document_processing_llm_calls', type_='foreignkey')
    op.create_foreign_key(None, 'document_processing_llm_calls', 'document_processing_runs', ['run_id'], ['id'])
    op.add_column('room_messages', sa.Column('llm_calls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_messages', 'llm_calls')
    op.drop_constraint(None, 'document_processing_llm_calls', type_='foreignkey')
    op.create_foreign_key(op.f('document_processing_llm_calls_run_id_fkey'), 'document_processing_llm_calls', 'document_processing_runs', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
