# type: ignore[reportAttributeAccessIssue]

"""add_type_to_room_messages

Revision ID: c518621e53f2
Revises: 61eedf71e215
Create Date: 2026-04-24 19:51:56.990023

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'c518621e53f2'
down_revision: Union[str, None] = '61eedf71e215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_messages', sa.Column('type', sa.String(), server_default='CHAT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_messages', 'type')
    # ### end Alembic commands ###
