# type: ignore[reportAttributeAccessIssue]

"""init

Revision ID: eab1d5b20a63
Revises: 
Create Date: 2026-04-22 22:13:39.343849

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eab1d5b20a63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PUBLISHED', name='scenariostatus').create(op.get_bind())
    sa.Enum('PREPARING', 'RUNNING', 'COMPLETED', name='roomstatus').create(op.get_bind())
    op.create_table('embedding_caches',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('model_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', 'model_key')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('validator_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validator_hash', name='uq_refresh_tokens_validator_hash')
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_players', sa.Integer(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('min_hours', sa.Float(), nullable=True),
    sa.Column('max_hours', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', name='scenariostatus', create_type=False), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('graph_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenarios_creator_id', 'scenarios', ['creator_id'], unique=False)
    op.create_table('documents',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('md_path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_scenario_id', 'documents', ['scenario_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embeddings_scenario_id', 'embeddings', ['scenario_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', postgresql.ENUM('PREPARING', 'RUNNING', 'COMPLETED', name='roomstatus', create_type=False), nullable=False),
    sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('graph_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rooms_host_id', 'rooms', ['host_id'], unique=False)
    op.create_table('facts',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_room_id', 'facts', ['room_id'], unique=False)
    op.create_table('room_messages',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_messages_room_id_created_at', 'room_messages', ['room_id', 'created_at'], unique=False)
    op.create_table('room_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_participants_room_id', 'room_participants', ['room_id'], unique=False)
    op.create_index('ix_room_participants_user_id', 'room_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_participants_user_id', table_name='room_participants')
    op.drop_index('ix_room_participants_room_id', table_name='room_participants')
    op.drop_table('room_participants')
    op.drop_index('ix_room_messages_room_id_created_at', table_name='room_messages')
    op.drop_table('room_messages')
    op.drop_index('ix_facts_room_id', table_name='facts')
    op.drop_table('facts')
    op.drop_index('ix_rooms_host_id', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_embeddings_scenario_id', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_documents_scenario_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_scenarios_creator_id', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_table('embedding_caches')
    sa.Enum('PREPARING', 'RUNNING', 'COMPLETED', name='roomstatus').drop(op.get_bind())
    sa.Enum('DRAFT', 'PUBLISHED', name='scenariostatus').drop(op.get_bind())
    # ### end Alembic commands ###
