# type: ignore[reportAttributeAccessIssue]

"""add document processing llm calls

Revision ID: 48102564a2c4
Revises: c831eb0ed613
Create Date: 2026-06-09 23:35:26.916641

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48102564a2c4'
down_revision: Union[str, None] = 'c831eb0ed613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('call_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['document_processing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_processing_llm_calls_run_id', 'document_processing_llm_calls', ['run_id'], unique=False)
    op.create_index('ix_document_processing_llm_calls_run_step_key', 'document_processing_llm_calls', ['run_id', 'step_id', 'call_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_processing_llm_calls_run_step_key', table_name='document_processing_llm_calls')
    op.drop_index('ix_document_processing_llm_calls_run_id', table_name='document_processing_llm_calls')
    op.drop_table('document_processing_llm_calls')
    # ### end Alembic commands ###
