# type: ignore[reportAttributeAccessIssue]

"""init

Revision ID: 72900583d718
Revises: c518621e53f2
Create Date: 2026-04-24 20:49:27.441147

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72900583d718'
down_revision: Union[str, None] = 'c518621e53f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('agent_history', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'agent_history')
    # ### end Alembic commands ###
