# type: ignore[reportAttributeAccessIssue]

"""add_character_id_to_room_participants

Revision ID: 61eedf71e215
Revises: a669e44179a5
Create Date: 2026-04-24 17:35:49.597769

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '61eedf71e215'
down_revision: Union[str, None] = 'a669e44179a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_participants', sa.Column('character_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'room_participants', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_participants', type_='foreignkey')
    op.drop_column('room_participants', 'character_id')
    # ### end Alembic commands ###
