# type: ignore[reportAttributeAccessIssue]

"""add_nickname_avatar_url_to_users

Revision ID: a669e44179a5
Revises: d5091025ff0b
Create Date: 2026-04-24 15:13:53.693452

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'a669e44179a5'
down_revision: Union[str, None] = 'd5091025ff0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
