# type: ignore[reportAttributeAccessIssue]

"""init

Revision ID: d5091025ff0b
Revises: d2b40fe497c4
Create Date: 2026-04-24 04:31:40.131193

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5091025ff0b'
down_revision: Union[str, None] = 'd2b40fe497c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('COC', 'DND', name='gamesystem').create(op.get_bind())
    op.create_table('characters',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('game_system', postgresql.ENUM('COC', 'DND', name='gamesystem', create_type=False), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_characters_owner_id', 'characters', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_characters_owner_id', table_name='characters')
    op.drop_table('characters')
    sa.Enum('COC', 'DND', name='gamesystem').drop(op.get_bind())
    # ### end Alembic commands ###
