# type: ignore[reportAttributeAccessIssue]

"""add document processing runs

Revision ID: d6a1a0bcdc6a
Revises: 72900583d718
Create Date: 2026-06-08 12:08:14.985844

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6a1a0bcdc6a'
down_revision: Union[str, None] = '72900583d718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='processingrunstatus').create(op.get_bind())
    op.create_table('document_processing_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', postgresql.ENUM('RUNNING', 'COMPLETED', 'FAILED', name='processingrunstatus', create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_document_processing_runs_document_id')
    )
    op.create_index('ix_document_processing_runs_document_id', 'document_processing_runs', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_processing_runs_document_id', table_name='document_processing_runs')
    op.drop_table('document_processing_runs')
    sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='processingrunstatus').drop(op.get_bind())
    # ### end Alembic commands ###
